// Generated by gencpp from file handcontrollerdemorosnode/changeHandTrackingMode.msg
// DO NOT EDIT!


#ifndef HANDCONTROLLERDEMOROSNODE_MESSAGE_CHANGEHANDTRACKINGMODE_H
#define HANDCONTROLLERDEMOROSNODE_MESSAGE_CHANGEHANDTRACKINGMODE_H

#include <ros/service_traits.h>


#include <handcontrollerdemorosnode/changeHandTrackingModeRequest.h>
#include <handcontrollerdemorosnode/changeHandTrackingModeResponse.h>


namespace handcontrollerdemorosnode
{

struct changeHandTrackingMode
{

typedef changeHandTrackingModeRequest Request;
typedef changeHandTrackingModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct changeHandTrackingMode
} // namespace handcontrollerdemorosnode


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::handcontrollerdemorosnode::changeHandTrackingMode > {
  static const char* value()
  {
    return "29d58f387352c15c4e4f5763022ae875";
  }

  static const char* value(const ::handcontrollerdemorosnode::changeHandTrackingMode&) { return value(); }
};

template<>
struct DataType< ::handcontrollerdemorosnode::changeHandTrackingMode > {
  static const char* value()
  {
    return "handcontrollerdemorosnode/changeHandTrackingMode";
  }

  static const char* value(const ::handcontrollerdemorosnode::changeHandTrackingMode&) { return value(); }
};


// service_traits::MD5Sum< ::handcontrollerdemorosnode::changeHandTrackingModeRequest> should match
// service_traits::MD5Sum< ::handcontrollerdemorosnode::changeHandTrackingMode >
template<>
struct MD5Sum< ::handcontrollerdemorosnode::changeHandTrackingModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::handcontrollerdemorosnode::changeHandTrackingMode >::value();
  }
  static const char* value(const ::handcontrollerdemorosnode::changeHandTrackingModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::handcontrollerdemorosnode::changeHandTrackingModeRequest> should match
// service_traits::DataType< ::handcontrollerdemorosnode::changeHandTrackingMode >
template<>
struct DataType< ::handcontrollerdemorosnode::changeHandTrackingModeRequest>
{
  static const char* value()
  {
    return DataType< ::handcontrollerdemorosnode::changeHandTrackingMode >::value();
  }
  static const char* value(const ::handcontrollerdemorosnode::changeHandTrackingModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::handcontrollerdemorosnode::changeHandTrackingModeResponse> should match
// service_traits::MD5Sum< ::handcontrollerdemorosnode::changeHandTrackingMode >
template<>
struct MD5Sum< ::handcontrollerdemorosnode::changeHandTrackingModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::handcontrollerdemorosnode::changeHandTrackingMode >::value();
  }
  static const char* value(const ::handcontrollerdemorosnode::changeHandTrackingModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::handcontrollerdemorosnode::changeHandTrackingModeResponse> should match
// service_traits::DataType< ::handcontrollerdemorosnode::changeHandTrackingMode >
template<>
struct DataType< ::handcontrollerdemorosnode::changeHandTrackingModeResponse>
{
  static const char* value()
  {
    return DataType< ::handcontrollerdemorosnode::changeHandTrackingMode >::value();
  }
  static const char* value(const ::handcontrollerdemorosnode::changeHandTrackingModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HANDCONTROLLERDEMOROSNODE_MESSAGE_CHANGEHANDTRACKINGMODE_H
