// Generated by gencpp from file handcontrollerdemorosnode/controlEndHand.msg
// DO NOT EDIT!


#ifndef HANDCONTROLLERDEMOROSNODE_MESSAGE_CONTROLENDHAND_H
#define HANDCONTROLLERDEMOROSNODE_MESSAGE_CONTROLENDHAND_H

#include <ros/service_traits.h>


#include <handcontrollerdemorosnode/controlEndHandRequest.h>
#include <handcontrollerdemorosnode/controlEndHandResponse.h>


namespace handcontrollerdemorosnode
{

struct controlEndHand
{

typedef controlEndHandRequest Request;
typedef controlEndHandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct controlEndHand
} // namespace handcontrollerdemorosnode


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::handcontrollerdemorosnode::controlEndHand > {
  static const char* value()
  {
    return "741989817a59889e258aa9e94c7ada8a";
  }

  static const char* value(const ::handcontrollerdemorosnode::controlEndHand&) { return value(); }
};

template<>
struct DataType< ::handcontrollerdemorosnode::controlEndHand > {
  static const char* value()
  {
    return "handcontrollerdemorosnode/controlEndHand";
  }

  static const char* value(const ::handcontrollerdemorosnode::controlEndHand&) { return value(); }
};


// service_traits::MD5Sum< ::handcontrollerdemorosnode::controlEndHandRequest> should match
// service_traits::MD5Sum< ::handcontrollerdemorosnode::controlEndHand >
template<>
struct MD5Sum< ::handcontrollerdemorosnode::controlEndHandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::handcontrollerdemorosnode::controlEndHand >::value();
  }
  static const char* value(const ::handcontrollerdemorosnode::controlEndHandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::handcontrollerdemorosnode::controlEndHandRequest> should match
// service_traits::DataType< ::handcontrollerdemorosnode::controlEndHand >
template<>
struct DataType< ::handcontrollerdemorosnode::controlEndHandRequest>
{
  static const char* value()
  {
    return DataType< ::handcontrollerdemorosnode::controlEndHand >::value();
  }
  static const char* value(const ::handcontrollerdemorosnode::controlEndHandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::handcontrollerdemorosnode::controlEndHandResponse> should match
// service_traits::MD5Sum< ::handcontrollerdemorosnode::controlEndHand >
template<>
struct MD5Sum< ::handcontrollerdemorosnode::controlEndHandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::handcontrollerdemorosnode::controlEndHand >::value();
  }
  static const char* value(const ::handcontrollerdemorosnode::controlEndHandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::handcontrollerdemorosnode::controlEndHandResponse> should match
// service_traits::DataType< ::handcontrollerdemorosnode::controlEndHand >
template<>
struct DataType< ::handcontrollerdemorosnode::controlEndHandResponse>
{
  static const char* value()
  {
    return DataType< ::handcontrollerdemorosnode::controlEndHand >::value();
  }
  static const char* value(const ::handcontrollerdemorosnode::controlEndHandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HANDCONTROLLERDEMOROSNODE_MESSAGE_CONTROLENDHAND_H
