// Generated by gencpp from file handcontrollerdemorosnode/controlEndHandRequest.msg
// DO NOT EDIT!


#ifndef HANDCONTROLLERDEMOROSNODE_MESSAGE_CONTROLENDHANDREQUEST_H
#define HANDCONTROLLERDEMOROSNODE_MESSAGE_CONTROLENDHANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace handcontrollerdemorosnode
{
template <class ContainerAllocator>
struct controlEndHandRequest_
{
  typedef controlEndHandRequest_<ContainerAllocator> Type;

  controlEndHandRequest_()
    : left_hand_position()
    , right_hand_position()  {
    }
  controlEndHandRequest_(const ContainerAllocator& _alloc)
    : left_hand_position(_alloc)
    , right_hand_position(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _left_hand_position_type;
  _left_hand_position_type left_hand_position;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _right_hand_position_type;
  _right_hand_position_type right_hand_position;





  typedef boost::shared_ptr< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct controlEndHandRequest_

typedef ::handcontrollerdemorosnode::controlEndHandRequest_<std::allocator<void> > controlEndHandRequest;

typedef boost::shared_ptr< ::handcontrollerdemorosnode::controlEndHandRequest > controlEndHandRequestPtr;
typedef boost::shared_ptr< ::handcontrollerdemorosnode::controlEndHandRequest const> controlEndHandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator1> & lhs, const ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.left_hand_position == rhs.left_hand_position &&
    lhs.right_hand_position == rhs.right_hand_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator1> & lhs, const ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace handcontrollerdemorosnode

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1790ef3209367c45321962dc0cfca107";
  }

  static const char* value(const ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1790ef3209367c45ULL;
  static const uint64_t static_value2 = 0x321962dc0cfca107ULL;
};

template<class ContainerAllocator>
struct DataType< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "handcontrollerdemorosnode/controlEndHandRequest";
  }

  static const char* value(const ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] left_hand_position\n"
"uint8[] right_hand_position\n"
;
  }

  static const char* value(const ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_hand_position);
      stream.next(m.right_hand_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct controlEndHandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::handcontrollerdemorosnode::controlEndHandRequest_<ContainerAllocator>& v)
  {
    s << indent << "left_hand_position[]" << std::endl;
    for (size_t i = 0; i < v.left_hand_position.size(); ++i)
    {
      s << indent << "  left_hand_position[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.left_hand_position[i]);
    }
    s << indent << "right_hand_position[]" << std::endl;
    for (size_t i = 0; i < v.right_hand_position.size(); ++i)
    {
      s << indent << "  right_hand_position[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.right_hand_position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HANDCONTROLLERDEMOROSNODE_MESSAGE_CONTROLENDHANDREQUEST_H
