// Generated by gencpp from file handcontrollerdemorosnode/srvArmIK.msg
// DO NOT EDIT!


#ifndef HANDCONTROLLERDEMOROSNODE_MESSAGE_SRVARMIK_H
#define HANDCONTROLLERDEMOROSNODE_MESSAGE_SRVARMIK_H

#include <ros/service_traits.h>


#include <handcontrollerdemorosnode/srvArmIKRequest.h>
#include <handcontrollerdemorosnode/srvArmIKResponse.h>


namespace handcontrollerdemorosnode
{

struct srvArmIK
{

typedef srvArmIKRequest Request;
typedef srvArmIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvArmIK
} // namespace handcontrollerdemorosnode


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::handcontrollerdemorosnode::srvArmIK > {
  static const char* value()
  {
    return "2b5b0516bd664187d5eefa858c0bc7ee";
  }

  static const char* value(const ::handcontrollerdemorosnode::srvArmIK&) { return value(); }
};

template<>
struct DataType< ::handcontrollerdemorosnode::srvArmIK > {
  static const char* value()
  {
    return "handcontrollerdemorosnode/srvArmIK";
  }

  static const char* value(const ::handcontrollerdemorosnode::srvArmIK&) { return value(); }
};


// service_traits::MD5Sum< ::handcontrollerdemorosnode::srvArmIKRequest> should match
// service_traits::MD5Sum< ::handcontrollerdemorosnode::srvArmIK >
template<>
struct MD5Sum< ::handcontrollerdemorosnode::srvArmIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::handcontrollerdemorosnode::srvArmIK >::value();
  }
  static const char* value(const ::handcontrollerdemorosnode::srvArmIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::handcontrollerdemorosnode::srvArmIKRequest> should match
// service_traits::DataType< ::handcontrollerdemorosnode::srvArmIK >
template<>
struct DataType< ::handcontrollerdemorosnode::srvArmIKRequest>
{
  static const char* value()
  {
    return DataType< ::handcontrollerdemorosnode::srvArmIK >::value();
  }
  static const char* value(const ::handcontrollerdemorosnode::srvArmIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::handcontrollerdemorosnode::srvArmIKResponse> should match
// service_traits::MD5Sum< ::handcontrollerdemorosnode::srvArmIK >
template<>
struct MD5Sum< ::handcontrollerdemorosnode::srvArmIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::handcontrollerdemorosnode::srvArmIK >::value();
  }
  static const char* value(const ::handcontrollerdemorosnode::srvArmIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::handcontrollerdemorosnode::srvArmIKResponse> should match
// service_traits::DataType< ::handcontrollerdemorosnode::srvArmIK >
template<>
struct DataType< ::handcontrollerdemorosnode::srvArmIKResponse>
{
  static const char* value()
  {
    return DataType< ::handcontrollerdemorosnode::srvArmIK >::value();
  }
  static const char* value(const ::handcontrollerdemorosnode::srvArmIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HANDCONTROLLERDEMOROSNODE_MESSAGE_SRVARMIK_H
