// Generated by gencpp from file noitom_hi5_hand_udp_python/QuaternionArray.msg
// DO NOT EDIT!


#ifndef NOITOM_HI5_HAND_UDP_PYTHON_MESSAGE_QUATERNIONARRAY_H
#define NOITOM_HI5_HAND_UDP_PYTHON_MESSAGE_QUATERNIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Quaternion.h>

namespace noitom_hi5_hand_udp_python
{
template <class ContainerAllocator>
struct QuaternionArray_
{
  typedef QuaternionArray_<ContainerAllocator> Type;

  QuaternionArray_()
    : quaternions()  {
    }
  QuaternionArray_(const ContainerAllocator& _alloc)
    : quaternions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Quaternion_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Quaternion_<ContainerAllocator> >> _quaternions_type;
  _quaternions_type quaternions;





  typedef boost::shared_ptr< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> const> ConstPtr;

}; // struct QuaternionArray_

typedef ::noitom_hi5_hand_udp_python::QuaternionArray_<std::allocator<void> > QuaternionArray;

typedef boost::shared_ptr< ::noitom_hi5_hand_udp_python::QuaternionArray > QuaternionArrayPtr;
typedef boost::shared_ptr< ::noitom_hi5_hand_udp_python::QuaternionArray const> QuaternionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator1> & lhs, const ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator2> & rhs)
{
  return lhs.quaternions == rhs.quaternions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator1> & lhs, const ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace noitom_hi5_hand_udp_python

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c666021c5a7330bd53d9827c2e91d9f6";
  }

  static const char* value(const ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc666021c5a7330bdULL;
  static const uint64_t static_value2 = 0x53d9827c2e91d9f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "noitom_hi5_hand_udp_python/QuaternionArray";
  }

  static const char* value(const ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Quaternion[] quaternions\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.quaternions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuaternionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::noitom_hi5_hand_udp_python::QuaternionArray_<ContainerAllocator>& v)
  {
    s << indent << "quaternions[]" << std::endl;
    for (size_t i = 0; i < v.quaternions.size(); ++i)
    {
      s << indent << "  quaternions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "    ", v.quaternions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOITOM_HI5_HAND_UDP_PYTHON_MESSAGE_QUATERNIONARRAY_H
