(cl:defpackage h12pro_controller_node-msg
  (:use )
  (:export
   "<ECJOINTMOTORDATA>"
   "ECJOINTMOTORDATA"
   "<ROBOTACTIONSTATE>"
   "ROBOTACTIONSTATE"
   "<H12PROREMOTECONTROLLERCHANNEL>"
   "H12PROREMOTECONTROLLERCHANNEL"
   "<ROBOTPHASE>"
   "ROBOTPHASE"
   "<ROBOTQVTAU>"
   "ROBOTQVTAU"
   "<ROBOTTORSOSTATE>"
   "ROBOTTORSOSTATE"
   "<WALKCOMMAND>"
   "WALKCOMMAND"
  ))

