# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from noitom_hi5_hand_udp_python/handRotationEular.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import noitom_hi5_hand_udp_python.msg

class handRotationEular(genpy.Message):
  _md5sum = "75ea7fdfd1913bbabb0a96c424b42024"
  _type = "noitom_hi5_hand_udp_python/handRotationEular"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """noitom_hi5_hand_udp_python/Vector4[] eulerAngles

================================================================================
MSG: noitom_hi5_hand_udp_python/Vector4
float32 x
float32 y
float32 z
float32 w"""
  __slots__ = ['eulerAngles']
  _slot_types = ['noitom_hi5_hand_udp_python/Vector4[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       eulerAngles

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(handRotationEular, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.eulerAngles is None:
        self.eulerAngles = []
    else:
      self.eulerAngles = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.eulerAngles)
      buff.write(_struct_I.pack(length))
      for val1 in self.eulerAngles:
        _x = val1
        buff.write(_get_struct_4f().pack(_x.x, _x.y, _x.z, _x.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.eulerAngles is None:
        self.eulerAngles = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.eulerAngles = []
      for i in range(0, length):
        val1 = noitom_hi5_hand_udp_python.msg.Vector4()
        _x = val1
        start = end
        end += 16
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4f().unpack(str[start:end])
        self.eulerAngles.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.eulerAngles)
      buff.write(_struct_I.pack(length))
      for val1 in self.eulerAngles:
        _x = val1
        buff.write(_get_struct_4f().pack(_x.x, _x.y, _x.z, _x.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.eulerAngles is None:
        self.eulerAngles = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.eulerAngles = []
      for i in range(0, length):
        val1 = noitom_hi5_hand_udp_python.msg.Vector4()
        _x = val1
        start = end
        end += 16
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4f().unpack(str[start:end])
        self.eulerAngles.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
