(cl:defpackage kuavo_ros_interfaces-srv
  (:use )
  (:export
   "OCS2CHANGEARMCTRLMODE"
   "<OCS2CHANGEARMCTRLMODE-REQUEST>"
   "OCS2CHANGEARMCTRLMODE-REQUEST"
   "<OCS2CHANGEARMCTRLMODE-RESPONSE>"
   "OCS2CHANGEARMCTRLMODE-RESPONSE"
   "PLANARMTRAJECTORYBEZIERCURVE"
   "<PLANARMTRAJECTORYBEZIERCURVE-REQUEST>"
   "PLANARMTRAJECTORYBEZIERCURVE-REQUEST"
   "<PLANARMTRAJECTORYBEZIERCURVE-RESPONSE>"
   "PLANARMTRAJECTORYBEZIERCURVE-RESPONSE"
   "STOPPLANARMTRAJECTORY"
   "<STOPPLANARMTRAJECTORY-REQUEST>"
   "STOPPLANARMTRAJECTORY-REQUEST"
   "<STOPPLANARMTRAJECTORY-RESPONSE>"
   "STOPPLANARMTRAJECTORY-RESPONSE"
  ))

