(cl:defpackage handcontrollerdemorosnode-msg
  (:use )
  (:export
   "<ARMPOSEWITHTIMESTAMP>"
   "ARMPOSEWITHTIMESTAMP"
   "<HANDROTATIONEULAR>"
   "HANDROTATIONEULAR"
   "<ROBOTARMPOSE>"
   "ROBOTARMPOSE"
   "<ROBOTHANDPOSITION>"
   "ROBOTHANDPOSITION"
  ))

