joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500
  joint_names:
    - leg_l1_joint
    - leg_l2_joint
    - leg_l3_joint
    - leg_l4_joint
    - leg_l5_joint
    - leg_l6_joint
    - leg_r1_joint
    - leg_r2_joint
    - leg_r3_joint
    - leg_r4_joint
    - leg_r5_joint
    - leg_r6_joint
    - zarm_l1_joint
    - zarm_l2_joint
    - zarm_l3_joint
    - zarm_l4_joint
    - zarm_l5_joint
    - zarm_l6_joint
    - zarm_l7_joint
    - zarm_r1_joint
    - zarm_r2_joint
    - zarm_r3_joint
    - zarm_r4_joint
    - zarm_r5_joint
    - zarm_r6_joint
    - zarm_r7_joint
    - neck_joint_yaw
    - neck_joint_pitch
    
limbs_effort_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - leg_l1_joint
    - leg_l2_joint
    - leg_l3_joint
    - leg_l4_joint
    - leg_l5_joint
    - leg_l6_joint

    - leg_r1_joint
    - leg_r2_joint
    - leg_r3_joint
    - leg_r4_joint
    - leg_r5_joint
    - leg_r6_joint

    - zarm_l1_joint
    - zarm_l2_joint
    - zarm_l3_joint
    - zarm_l4_joint
    - zarm_l5_joint
    - zarm_l6_joint
    - zarm_l7_joint

    - zarm_r1_joint
    - zarm_r2_joint
    - zarm_r3_joint
    - zarm_r4_joint
    - zarm_r5_joint
    - zarm_r6_joint
    - zarm_r7_joint
    - neck_joint_yaw
    - neck_joint_pitch

  interface_name: "hardware_interface/EffortJointInterface"

joint_position_controller:
  type: "position_controllers/JointPositionController"
  joint_names:
    - leg_l1_joint
    - leg_l2_joint
    - leg_l3_joint
    - leg_l4_joint
    - leg_l5_joint
    - leg_l6_joint

    - leg_r1_joint
    - leg_r2_joint
    - leg_r3_joint
    - leg_r4_joint
    - leg_r5_joint
    - leg_r6_joint

    - zarm_l1_joint
    - zarm_l2_joint
    - zarm_l3_joint
    - zarm_l4_joint
    - zarm_l5_joint
    - zarm_l6_joint
    - zarm_l7_joint

    - zarm_r1_joint
    - zarm_r2_joint
    - zarm_r3_joint
    - zarm_r4_joint
    - zarm_r5_joint
    - zarm_r6_joint
    - zarm_r7_joint
    - neck_joint_yaw
    - neck_joint_pitch
