(cl:in-package ocs2_msgs-msg)
(cl:export '(INITTIME-VAL
          INITTIME
          INITSTATE-VAL
          INITSTATE
          FINALTIME-VAL
          FINALTIME
          MODESCHEDULE-VAL
          MODESCHEDULE
          TARGETTRAJECTORIES-VAL
          TARGETTRAJECTORIES
          MPC_FLATTENED_CONTROLLER-VAL
          MPC_FLATTENED_CONTROLLER
          SWINGPLANNERMULTIPLIERS-VAL
          SWINGPLANNERMULTIPLIERS
))