// Generated by gencpp from file kuavo_msgs/armTargetPoses.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_ARMTARGETPOSES_H
#define KUAVO_MSGS_MESSAGE_ARMTARGETPOSES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_msgs
{
template <class ContainerAllocator>
struct armTargetPoses_
{
  typedef armTargetPoses_<ContainerAllocator> Type;

  armTargetPoses_()
    : times()
    , values()  {
    }
  armTargetPoses_(const ContainerAllocator& _alloc)
    : times(_alloc)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _times_type;
  _times_type times;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> const> ConstPtr;

}; // struct armTargetPoses_

typedef ::kuavo_msgs::armTargetPoses_<std::allocator<void> > armTargetPoses;

typedef boost::shared_ptr< ::kuavo_msgs::armTargetPoses > armTargetPosesPtr;
typedef boost::shared_ptr< ::kuavo_msgs::armTargetPoses const> armTargetPosesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_msgs::armTargetPoses_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_msgs::armTargetPoses_<ContainerAllocator1> & lhs, const ::kuavo_msgs::armTargetPoses_<ContainerAllocator2> & rhs)
{
  return lhs.times == rhs.times &&
    lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_msgs::armTargetPoses_<ContainerAllocator1> & lhs, const ::kuavo_msgs::armTargetPoses_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "267055a1a7e685e90c17a3ebf7a8a26c";
  }

  static const char* value(const ::kuavo_msgs::armTargetPoses_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x267055a1a7e685e9ULL;
  static const uint64_t static_value2 = 0x0c17a3ebf7a8a26cULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_msgs/armTargetPoses";
  }

  static const char* value(const ::kuavo_msgs::armTargetPoses_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# times: times series\n"
"# values: values matrix\n"
"float64[] times\n"
"float64[] values\n"
;
  }

  static const char* value(const ::kuavo_msgs::armTargetPoses_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.times);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct armTargetPoses_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_msgs::armTargetPoses_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_msgs::armTargetPoses_<ContainerAllocator>& v)
  {
    s << indent << "times[]" << std::endl;
    for (size_t i = 0; i < v.times.size(); ++i)
    {
      s << indent << "  times[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.times[i]);
    }
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_ARMTARGETPOSES_H
