// Generated by gencpp from file kuavo_msgs/changeTorsoCtrlModeRequest.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_CHANGETORSOCTRLMODEREQUEST_H
#define KUAVO_MSGS_MESSAGE_CHANGETORSOCTRLMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_msgs
{
template <class ContainerAllocator>
struct changeTorsoCtrlModeRequest_
{
  typedef changeTorsoCtrlModeRequest_<ContainerAllocator> Type;

  changeTorsoCtrlModeRequest_()
    : control_mode(0)  {
    }
  changeTorsoCtrlModeRequest_(const ContainerAllocator& _alloc)
    : control_mode(0)  {
  (void)_alloc;
    }



   typedef int32_t _control_mode_type;
  _control_mode_type control_mode;





  typedef boost::shared_ptr< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct changeTorsoCtrlModeRequest_

typedef ::kuavo_msgs::changeTorsoCtrlModeRequest_<std::allocator<void> > changeTorsoCtrlModeRequest;

typedef boost::shared_ptr< ::kuavo_msgs::changeTorsoCtrlModeRequest > changeTorsoCtrlModeRequestPtr;
typedef boost::shared_ptr< ::kuavo_msgs::changeTorsoCtrlModeRequest const> changeTorsoCtrlModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator1> & lhs, const ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.control_mode == rhs.control_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator1> & lhs, const ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f5907fdb226711da233100c712cc0eb";
  }

  static const char* value(const ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f5907fdb226711dULL;
  static const uint64_t static_value2 = 0xa233100c712cc0ebULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_msgs/changeTorsoCtrlModeRequest";
  }

  static const char* value(const ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 control_mode # 0: control 6dof, 1: control height+yaw+pitch, 2: control control height+pitch \n"
;
  }

  static const char* value(const ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct changeTorsoCtrlModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_msgs::changeTorsoCtrlModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "control_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.control_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_CHANGETORSOCTRLMODEREQUEST_H
