// Generated by gencpp from file kuavo_msgs/changeArmCtrlMode.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_CHANGEARMCTRLMODE_H
#define KUAVO_MSGS_MESSAGE_CHANGEARMCTRLMODE_H

#include <ros/service_traits.h>


#include <kuavo_msgs/changeArmCtrlModeRequest.h>
#include <kuavo_msgs/changeArmCtrlModeResponse.h>


namespace kuavo_msgs
{

struct changeArmCtrlMode
{

typedef changeArmCtrlModeRequest Request;
typedef changeArmCtrlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct changeArmCtrlMode
} // namespace kuavo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_msgs::changeArmCtrlMode > {
  static const char* value()
  {
    return "8a8d154c05ee16e8f5d2b72d9bb51026";
  }

  static const char* value(const ::kuavo_msgs::changeArmCtrlMode&) { return value(); }
};

template<>
struct DataType< ::kuavo_msgs::changeArmCtrlMode > {
  static const char* value()
  {
    return "kuavo_msgs/changeArmCtrlMode";
  }

  static const char* value(const ::kuavo_msgs::changeArmCtrlMode&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_msgs::changeArmCtrlModeRequest> should match
// service_traits::MD5Sum< ::kuavo_msgs::changeArmCtrlMode >
template<>
struct MD5Sum< ::kuavo_msgs::changeArmCtrlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::changeArmCtrlMode >::value();
  }
  static const char* value(const ::kuavo_msgs::changeArmCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::changeArmCtrlModeRequest> should match
// service_traits::DataType< ::kuavo_msgs::changeArmCtrlMode >
template<>
struct DataType< ::kuavo_msgs::changeArmCtrlModeRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::changeArmCtrlMode >::value();
  }
  static const char* value(const ::kuavo_msgs::changeArmCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_msgs::changeArmCtrlModeResponse> should match
// service_traits::MD5Sum< ::kuavo_msgs::changeArmCtrlMode >
template<>
struct MD5Sum< ::kuavo_msgs::changeArmCtrlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::changeArmCtrlMode >::value();
  }
  static const char* value(const ::kuavo_msgs::changeArmCtrlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::changeArmCtrlModeResponse> should match
// service_traits::DataType< ::kuavo_msgs::changeArmCtrlMode >
template<>
struct DataType< ::kuavo_msgs::changeArmCtrlModeResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::changeArmCtrlMode >::value();
  }
  static const char* value(const ::kuavo_msgs::changeArmCtrlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_CHANGEARMCTRLMODE_H
