// Generated by gencpp from file kuavo_msgs/changeTorsoCtrlMode.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_CHANGETORSOCTRLMODE_H
#define KUAVO_MSGS_MESSAGE_CHANGETORSOCTRLMODE_H

#include <ros/service_traits.h>


#include <kuavo_msgs/changeTorsoCtrlModeRequest.h>
#include <kuavo_msgs/changeTorsoCtrlModeResponse.h>


namespace kuavo_msgs
{

struct changeTorsoCtrlMode
{

typedef changeTorsoCtrlModeRequest Request;
typedef changeTorsoCtrlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct changeTorsoCtrlMode
} // namespace kuavo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_msgs::changeTorsoCtrlMode > {
  static const char* value()
  {
    return "8a8d154c05ee16e8f5d2b72d9bb51026";
  }

  static const char* value(const ::kuavo_msgs::changeTorsoCtrlMode&) { return value(); }
};

template<>
struct DataType< ::kuavo_msgs::changeTorsoCtrlMode > {
  static const char* value()
  {
    return "kuavo_msgs/changeTorsoCtrlMode";
  }

  static const char* value(const ::kuavo_msgs::changeTorsoCtrlMode&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_msgs::changeTorsoCtrlModeRequest> should match
// service_traits::MD5Sum< ::kuavo_msgs::changeTorsoCtrlMode >
template<>
struct MD5Sum< ::kuavo_msgs::changeTorsoCtrlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::changeTorsoCtrlMode >::value();
  }
  static const char* value(const ::kuavo_msgs::changeTorsoCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::changeTorsoCtrlModeRequest> should match
// service_traits::DataType< ::kuavo_msgs::changeTorsoCtrlMode >
template<>
struct DataType< ::kuavo_msgs::changeTorsoCtrlModeRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::changeTorsoCtrlMode >::value();
  }
  static const char* value(const ::kuavo_msgs::changeTorsoCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_msgs::changeTorsoCtrlModeResponse> should match
// service_traits::MD5Sum< ::kuavo_msgs::changeTorsoCtrlMode >
template<>
struct MD5Sum< ::kuavo_msgs::changeTorsoCtrlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::changeTorsoCtrlMode >::value();
  }
  static const char* value(const ::kuavo_msgs::changeTorsoCtrlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::changeTorsoCtrlModeResponse> should match
// service_traits::DataType< ::kuavo_msgs::changeTorsoCtrlMode >
template<>
struct DataType< ::kuavo_msgs::changeTorsoCtrlModeResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::changeTorsoCtrlMode >::value();
  }
  static const char* value(const ::kuavo_msgs::changeTorsoCtrlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_CHANGETORSOCTRLMODE_H
