// Generated by gencpp from file kuavo_msgs/enableHandTouchSensor.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_ENABLEHANDTOUCHSENSOR_H
#define KUAVO_MSGS_MESSAGE_ENABLEHANDTOUCHSENSOR_H

#include <ros/service_traits.h>


#include <kuavo_msgs/enableHandTouchSensorRequest.h>
#include <kuavo_msgs/enableHandTouchSensorResponse.h>


namespace kuavo_msgs
{

struct enableHandTouchSensor
{

typedef enableHandTouchSensorRequest Request;
typedef enableHandTouchSensorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct enableHandTouchSensor
} // namespace kuavo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_msgs::enableHandTouchSensor > {
  static const char* value()
  {
    return "710f3d70d245856e41b01f7ffef21580";
  }

  static const char* value(const ::kuavo_msgs::enableHandTouchSensor&) { return value(); }
};

template<>
struct DataType< ::kuavo_msgs::enableHandTouchSensor > {
  static const char* value()
  {
    return "kuavo_msgs/enableHandTouchSensor";
  }

  static const char* value(const ::kuavo_msgs::enableHandTouchSensor&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_msgs::enableHandTouchSensorRequest> should match
// service_traits::MD5Sum< ::kuavo_msgs::enableHandTouchSensor >
template<>
struct MD5Sum< ::kuavo_msgs::enableHandTouchSensorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::enableHandTouchSensor >::value();
  }
  static const char* value(const ::kuavo_msgs::enableHandTouchSensorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::enableHandTouchSensorRequest> should match
// service_traits::DataType< ::kuavo_msgs::enableHandTouchSensor >
template<>
struct DataType< ::kuavo_msgs::enableHandTouchSensorRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::enableHandTouchSensor >::value();
  }
  static const char* value(const ::kuavo_msgs::enableHandTouchSensorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_msgs::enableHandTouchSensorResponse> should match
// service_traits::MD5Sum< ::kuavo_msgs::enableHandTouchSensor >
template<>
struct MD5Sum< ::kuavo_msgs::enableHandTouchSensorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::enableHandTouchSensor >::value();
  }
  static const char* value(const ::kuavo_msgs::enableHandTouchSensorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::enableHandTouchSensorResponse> should match
// service_traits::DataType< ::kuavo_msgs::enableHandTouchSensor >
template<>
struct DataType< ::kuavo_msgs::enableHandTouchSensorResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::enableHandTouchSensor >::value();
  }
  static const char* value(const ::kuavo_msgs::enableHandTouchSensorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_ENABLEHANDTOUCHSENSOR_H
