// Generated by gencpp from file kuavo_msgs/endEffectorData.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_ENDEFFECTORDATA_H
#define KUAVO_MSGS_MESSAGE_ENDEFFECTORDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_msgs
{
template <class ContainerAllocator>
struct endEffectorData_
{
  typedef endEffectorData_<ContainerAllocator> Type;

  endEffectorData_()
    : name()
    , position()
    , velocity()
    , effort()  {
    }
  endEffectorData_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , position(_alloc)
    , velocity(_alloc)
    , effort(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _name_type;
  _name_type name;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _position_type;
  _position_type position;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _velocity_type;
  _velocity_type velocity;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _effort_type;
  _effort_type effort;





  typedef boost::shared_ptr< ::kuavo_msgs::endEffectorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_msgs::endEffectorData_<ContainerAllocator> const> ConstPtr;

}; // struct endEffectorData_

typedef ::kuavo_msgs::endEffectorData_<std::allocator<void> > endEffectorData;

typedef boost::shared_ptr< ::kuavo_msgs::endEffectorData > endEffectorDataPtr;
typedef boost::shared_ptr< ::kuavo_msgs::endEffectorData const> endEffectorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_msgs::endEffectorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_msgs::endEffectorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_msgs::endEffectorData_<ContainerAllocator1> & lhs, const ::kuavo_msgs::endEffectorData_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.effort == rhs.effort;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_msgs::endEffectorData_<ContainerAllocator1> & lhs, const ::kuavo_msgs::endEffectorData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::endEffectorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::endEffectorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::endEffectorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::endEffectorData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::endEffectorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::endEffectorData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_msgs::endEffectorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5703dc153b077fbca188a602cb8df8ed";
  }

  static const char* value(const ::kuavo_msgs::endEffectorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5703dc153b077fbcULL;
  static const uint64_t static_value2 = 0xa188a602cb8df8edULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_msgs::endEffectorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_msgs/endEffectorData";
  }

  static const char* value(const ::kuavo_msgs::endEffectorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_msgs::endEffectorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] name  \n"
"float64[] position\n"
"float64[] velocity  \n"
"float64[] effort\n"
;
  }

  static const char* value(const ::kuavo_msgs::endEffectorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_msgs::endEffectorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.effort);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct endEffectorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_msgs::endEffectorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_msgs::endEffectorData_<ContainerAllocator>& v)
  {
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name[i]);
    }
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocity[i]);
    }
    s << indent << "effort[]" << std::endl;
    for (size_t i = 0; i < v.effort.size(); ++i)
    {
      s << indent << "  effort[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.effort[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_ENDEFFECTORDATA_H
