// Generated by gencpp from file kuavo_msgs/fkSrvResponse.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_FKSRVRESPONSE_H
#define KUAVO_MSGS_MESSAGE_FKSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kuavo_msgs/twoArmHandPose.h>

namespace kuavo_msgs
{
template <class ContainerAllocator>
struct fkSrvResponse_
{
  typedef fkSrvResponse_<ContainerAllocator> Type;

  fkSrvResponse_()
    : success(false)
    , hand_poses()  {
    }
  fkSrvResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , hand_poses(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef  ::kuavo_msgs::twoArmHandPose_<ContainerAllocator>  _hand_poses_type;
  _hand_poses_type hand_poses;





  typedef boost::shared_ptr< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct fkSrvResponse_

typedef ::kuavo_msgs::fkSrvResponse_<std::allocator<void> > fkSrvResponse;

typedef boost::shared_ptr< ::kuavo_msgs::fkSrvResponse > fkSrvResponsePtr;
typedef boost::shared_ptr< ::kuavo_msgs::fkSrvResponse const> fkSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_msgs::fkSrvResponse_<ContainerAllocator1> & lhs, const ::kuavo_msgs::fkSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.hand_poses == rhs.hand_poses;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_msgs::fkSrvResponse_<ContainerAllocator1> & lhs, const ::kuavo_msgs::fkSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0989ef9ed6b7b2e5e8a37c79ae6916d9";
  }

  static const char* value(const ::kuavo_msgs::fkSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0989ef9ed6b7b2e5ULL;
  static const uint64_t static_value2 = 0xe8a37c79ae6916d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_msgs/fkSrvResponse";
  }

  static const char* value(const ::kuavo_msgs::fkSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"twoArmHandPose  hand_poses\n"
"\n"
"================================================================================\n"
"MSG: kuavo_msgs/twoArmHandPose\n"
"Header header\n"
"armHandPose  left_pose\n"
"armHandPose  right_pose\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: kuavo_msgs/armHandPose\n"
"float64[3] pos_xyz\n"
"float64[4] quat_xyzw\n"
"\n"
"float64[3] elbow_pos_xyz\n"
"\n"
"float64[7] joint_angles\n"
;
  }

  static const char* value(const ::kuavo_msgs::fkSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.hand_poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fkSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_msgs::fkSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_msgs::fkSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "hand_poses: ";
    s << std::endl;
    Printer< ::kuavo_msgs::twoArmHandPose_<ContainerAllocator> >::stream(s, indent + "  ", v.hand_poses);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_FKSRVRESPONSE_H
