// Generated by gencpp from file kuavo_msgs/footPoseTargetTrajectoriesSrvResponse.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_FOOTPOSETARGETTRAJECTORIESSRVRESPONSE_H
#define KUAVO_MSGS_MESSAGE_FOOTPOSETARGETTRAJECTORIESSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_msgs
{
template <class ContainerAllocator>
struct footPoseTargetTrajectoriesSrvResponse_
{
  typedef footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> Type;

  footPoseTargetTrajectoriesSrvResponse_()
    : success(false)  {
    }
  footPoseTargetTrajectoriesSrvResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct footPoseTargetTrajectoriesSrvResponse_

typedef ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<std::allocator<void> > footPoseTargetTrajectoriesSrvResponse;

typedef boost::shared_ptr< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse > footPoseTargetTrajectoriesSrvResponsePtr;
typedef boost::shared_ptr< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse const> footPoseTargetTrajectoriesSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator1> & lhs, const ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator1> & lhs, const ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_msgs/footPoseTargetTrajectoriesSrvResponse";
  }

  static const char* value(const ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct footPoseTargetTrajectoriesSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_msgs::footPoseTargetTrajectoriesSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_FOOTPOSETARGETTRAJECTORIESSRVRESPONSE_H
