// Generated by gencpp from file kuavo_msgs/gestureExecuteStateRequest.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_GESTUREEXECUTESTATEREQUEST_H
#define KUAVO_MSGS_MESSAGE_GESTUREEXECUTESTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_msgs
{
template <class ContainerAllocator>
struct gestureExecuteStateRequest_
{
  typedef gestureExecuteStateRequest_<ContainerAllocator> Type;

  gestureExecuteStateRequest_()
    {
    }
  gestureExecuteStateRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct gestureExecuteStateRequest_

typedef ::kuavo_msgs::gestureExecuteStateRequest_<std::allocator<void> > gestureExecuteStateRequest;

typedef boost::shared_ptr< ::kuavo_msgs::gestureExecuteStateRequest > gestureExecuteStateRequestPtr;
typedef boost::shared_ptr< ::kuavo_msgs::gestureExecuteStateRequest const> gestureExecuteStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace kuavo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_msgs/gestureExecuteStateRequest";
  }

  static const char* value(const ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This service checks the status of a task.\n"
"# It is used to determine whether a task is currently executing and provides an additional message.\n"
"\n"
"# Request:\n"
"# (No request fields for this service)\n"
"\n"
"# Response:\n"
"# bool is_executing  # Indicates whether the task is currently executing.\n"
"# string message     # A message providing additional information (e.g., status details or error messages).\n"
"\n"
;
  }

  static const char* value(const ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gestureExecuteStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::kuavo_msgs::gestureExecuteStateRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_GESTUREEXECUTESTATEREQUEST_H
