// Generated by gencpp from file kuavo_msgs/gestureExecuteStateResponse.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_GESTUREEXECUTESTATERESPONSE_H
#define KUAVO_MSGS_MESSAGE_GESTUREEXECUTESTATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_msgs
{
template <class ContainerAllocator>
struct gestureExecuteStateResponse_
{
  typedef gestureExecuteStateResponse_<ContainerAllocator> Type;

  gestureExecuteStateResponse_()
    : is_executing(false)
    , message()  {
    }
  gestureExecuteStateResponse_(const ContainerAllocator& _alloc)
    : is_executing(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _is_executing_type;
  _is_executing_type is_executing;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct gestureExecuteStateResponse_

typedef ::kuavo_msgs::gestureExecuteStateResponse_<std::allocator<void> > gestureExecuteStateResponse;

typedef boost::shared_ptr< ::kuavo_msgs::gestureExecuteStateResponse > gestureExecuteStateResponsePtr;
typedef boost::shared_ptr< ::kuavo_msgs::gestureExecuteStateResponse const> gestureExecuteStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator1> & lhs, const ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.is_executing == rhs.is_executing &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator1> & lhs, const ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "340cb7a19883494e0e422f2964927053";
  }

  static const char* value(const ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x340cb7a19883494eULL;
  static const uint64_t static_value2 = 0x0e422f2964927053ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_msgs/gestureExecuteStateResponse";
  }

  static const char* value(const ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_executing\n"
"string message\n"
;
  }

  static const char* value(const ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_executing);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gestureExecuteStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_msgs::gestureExecuteStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "is_executing: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_executing);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_GESTUREEXECUTESTATERESPONSE_H
