// Generated by gencpp from file kuavo_msgs/gestureExecuteState.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_GESTUREEXECUTESTATE_H
#define KUAVO_MSGS_MESSAGE_GESTUREEXECUTESTATE_H

#include <ros/service_traits.h>


#include <kuavo_msgs/gestureExecuteStateRequest.h>
#include <kuavo_msgs/gestureExecuteStateResponse.h>


namespace kuavo_msgs
{

struct gestureExecuteState
{

typedef gestureExecuteStateRequest Request;
typedef gestureExecuteStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gestureExecuteState
} // namespace kuavo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_msgs::gestureExecuteState > {
  static const char* value()
  {
    return "340cb7a19883494e0e422f2964927053";
  }

  static const char* value(const ::kuavo_msgs::gestureExecuteState&) { return value(); }
};

template<>
struct DataType< ::kuavo_msgs::gestureExecuteState > {
  static const char* value()
  {
    return "kuavo_msgs/gestureExecuteState";
  }

  static const char* value(const ::kuavo_msgs::gestureExecuteState&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_msgs::gestureExecuteStateRequest> should match
// service_traits::MD5Sum< ::kuavo_msgs::gestureExecuteState >
template<>
struct MD5Sum< ::kuavo_msgs::gestureExecuteStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::gestureExecuteState >::value();
  }
  static const char* value(const ::kuavo_msgs::gestureExecuteStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::gestureExecuteStateRequest> should match
// service_traits::DataType< ::kuavo_msgs::gestureExecuteState >
template<>
struct DataType< ::kuavo_msgs::gestureExecuteStateRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::gestureExecuteState >::value();
  }
  static const char* value(const ::kuavo_msgs::gestureExecuteStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_msgs::gestureExecuteStateResponse> should match
// service_traits::MD5Sum< ::kuavo_msgs::gestureExecuteState >
template<>
struct MD5Sum< ::kuavo_msgs::gestureExecuteStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::gestureExecuteState >::value();
  }
  static const char* value(const ::kuavo_msgs::gestureExecuteStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::gestureExecuteStateResponse> should match
// service_traits::DataType< ::kuavo_msgs::gestureExecuteState >
template<>
struct DataType< ::kuavo_msgs::gestureExecuteStateResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::gestureExecuteState >::value();
  }
  static const char* value(const ::kuavo_msgs::gestureExecuteStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_GESTUREEXECUTESTATE_H
