// Generated by gencpp from file kuavo_msgs/gestureListResponse.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_GESTURELISTRESPONSE_H
#define KUAVO_MSGS_MESSAGE_GESTURELISTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <kuavo_msgs/gestureInfo.h>

namespace kuavo_msgs
{
template <class ContainerAllocator>
struct gestureListResponse_
{
  typedef gestureListResponse_<ContainerAllocator> Type;

  gestureListResponse_()
    : success(false)
    , gesture_count(0)
    , message()
    , gesture_infos()  {
    }
  gestureListResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , gesture_count(0)
    , message(_alloc)
    , gesture_infos(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef int32_t _gesture_count_type;
  _gesture_count_type gesture_count;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::vector< ::kuavo_msgs::gestureInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::kuavo_msgs::gestureInfo_<ContainerAllocator> >> _gesture_infos_type;
  _gesture_infos_type gesture_infos;





  typedef boost::shared_ptr< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> const> ConstPtr;

}; // struct gestureListResponse_

typedef ::kuavo_msgs::gestureListResponse_<std::allocator<void> > gestureListResponse;

typedef boost::shared_ptr< ::kuavo_msgs::gestureListResponse > gestureListResponsePtr;
typedef boost::shared_ptr< ::kuavo_msgs::gestureListResponse const> gestureListResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_msgs::gestureListResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_msgs::gestureListResponse_<ContainerAllocator1> & lhs, const ::kuavo_msgs::gestureListResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.gesture_count == rhs.gesture_count &&
    lhs.message == rhs.message &&
    lhs.gesture_infos == rhs.gesture_infos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_msgs::gestureListResponse_<ContainerAllocator1> & lhs, const ::kuavo_msgs::gestureListResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee839a0568f441526fe05bf2e2f25572";
  }

  static const char* value(const ::kuavo_msgs::gestureListResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee839a0568f44152ULL;
  static const uint64_t static_value2 = 0x6fe05bf2e2f25572ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_msgs/gestureListResponse";
  }

  static const char* value(const ::kuavo_msgs::gestureListResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"int32 gesture_count\n"
"string message\n"
"kuavo_msgs/gestureInfo[] gesture_infos\n"
"\n"
"================================================================================\n"
"MSG: kuavo_msgs/gestureInfo\n"
"# This message defines the information for a single gesture.\n"
"# It includes the name, a list of aliases, and a description of the gesture.\n"
"\n"
"# The name of the gesture.\n"
"string gesture_name\n"
"\n"
"# A list of aliases for the gesture. These can be alternative names or shortcuts.\n"
"string[] alias\n"
"\n"
"# A description of the gesture, providing more detailed information about its purpose and usage.\n"
"string description\n"
;
  }

  static const char* value(const ::kuavo_msgs::gestureListResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.gesture_count);
      stream.next(m.message);
      stream.next(m.gesture_infos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gestureListResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_msgs::gestureListResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_msgs::gestureListResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "gesture_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gesture_count);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "gesture_infos[]" << std::endl;
    for (size_t i = 0; i < v.gesture_infos.size(); ++i)
    {
      s << indent << "  gesture_infos[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::kuavo_msgs::gestureInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.gesture_infos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_GESTURELISTRESPONSE_H
