// Generated by gencpp from file kuavo_msgs/gestureList.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_GESTURELIST_H
#define KUAVO_MSGS_MESSAGE_GESTURELIST_H

#include <ros/service_traits.h>


#include <kuavo_msgs/gestureListRequest.h>
#include <kuavo_msgs/gestureListResponse.h>


namespace kuavo_msgs
{

struct gestureList
{

typedef gestureListRequest Request;
typedef gestureListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gestureList
} // namespace kuavo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_msgs::gestureList > {
  static const char* value()
  {
    return "ee839a0568f441526fe05bf2e2f25572";
  }

  static const char* value(const ::kuavo_msgs::gestureList&) { return value(); }
};

template<>
struct DataType< ::kuavo_msgs::gestureList > {
  static const char* value()
  {
    return "kuavo_msgs/gestureList";
  }

  static const char* value(const ::kuavo_msgs::gestureList&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_msgs::gestureListRequest> should match
// service_traits::MD5Sum< ::kuavo_msgs::gestureList >
template<>
struct MD5Sum< ::kuavo_msgs::gestureListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::gestureList >::value();
  }
  static const char* value(const ::kuavo_msgs::gestureListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::gestureListRequest> should match
// service_traits::DataType< ::kuavo_msgs::gestureList >
template<>
struct DataType< ::kuavo_msgs::gestureListRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::gestureList >::value();
  }
  static const char* value(const ::kuavo_msgs::gestureListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_msgs::gestureListResponse> should match
// service_traits::MD5Sum< ::kuavo_msgs::gestureList >
template<>
struct MD5Sum< ::kuavo_msgs::gestureListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::gestureList >::value();
  }
  static const char* value(const ::kuavo_msgs::gestureListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::gestureListResponse> should match
// service_traits::DataType< ::kuavo_msgs::gestureList >
template<>
struct DataType< ::kuavo_msgs::gestureListResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::gestureList >::value();
  }
  static const char* value(const ::kuavo_msgs::gestureListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_GESTURELIST_H
