// Generated by gencpp from file kuavo_msgs/getCurrentGaitName.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_GETCURRENTGAITNAME_H
#define KUAVO_MSGS_MESSAGE_GETCURRENTGAITNAME_H

#include <ros/service_traits.h>


#include <kuavo_msgs/getCurrentGaitNameRequest.h>
#include <kuavo_msgs/getCurrentGaitNameResponse.h>


namespace kuavo_msgs
{

struct getCurrentGaitName
{

typedef getCurrentGaitNameRequest Request;
typedef getCurrentGaitNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getCurrentGaitName
} // namespace kuavo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_msgs::getCurrentGaitName > {
  static const char* value()
  {
    return "657f58245742fcfc53dd6ab5bfa3063e";
  }

  static const char* value(const ::kuavo_msgs::getCurrentGaitName&) { return value(); }
};

template<>
struct DataType< ::kuavo_msgs::getCurrentGaitName > {
  static const char* value()
  {
    return "kuavo_msgs/getCurrentGaitName";
  }

  static const char* value(const ::kuavo_msgs::getCurrentGaitName&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_msgs::getCurrentGaitNameRequest> should match
// service_traits::MD5Sum< ::kuavo_msgs::getCurrentGaitName >
template<>
struct MD5Sum< ::kuavo_msgs::getCurrentGaitNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::getCurrentGaitName >::value();
  }
  static const char* value(const ::kuavo_msgs::getCurrentGaitNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::getCurrentGaitNameRequest> should match
// service_traits::DataType< ::kuavo_msgs::getCurrentGaitName >
template<>
struct DataType< ::kuavo_msgs::getCurrentGaitNameRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::getCurrentGaitName >::value();
  }
  static const char* value(const ::kuavo_msgs::getCurrentGaitNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_msgs::getCurrentGaitNameResponse> should match
// service_traits::MD5Sum< ::kuavo_msgs::getCurrentGaitName >
template<>
struct MD5Sum< ::kuavo_msgs::getCurrentGaitNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::getCurrentGaitName >::value();
  }
  static const char* value(const ::kuavo_msgs::getCurrentGaitNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::getCurrentGaitNameResponse> should match
// service_traits::DataType< ::kuavo_msgs::getCurrentGaitName >
template<>
struct DataType< ::kuavo_msgs::getCurrentGaitNameResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::getCurrentGaitName >::value();
  }
  static const char* value(const ::kuavo_msgs::getCurrentGaitNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_GETCURRENTGAITNAME_H
