// Generated by gencpp from file kuavo_msgs/handForceLevelResponse.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_HANDFORCELEVELRESPONSE_H
#define KUAVO_MSGS_MESSAGE_HANDFORCELEVELRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_msgs
{
template <class ContainerAllocator>
struct handForceLevelResponse_
{
  typedef handForceLevelResponse_<ContainerAllocator> Type;

  handForceLevelResponse_()
    : success(false)
    , message()
    , force_level()  {
    }
  handForceLevelResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , force_level(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::vector<int8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int8_t>> _force_level_type;
  _force_level_type force_level;





  typedef boost::shared_ptr< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> const> ConstPtr;

}; // struct handForceLevelResponse_

typedef ::kuavo_msgs::handForceLevelResponse_<std::allocator<void> > handForceLevelResponse;

typedef boost::shared_ptr< ::kuavo_msgs::handForceLevelResponse > handForceLevelResponsePtr;
typedef boost::shared_ptr< ::kuavo_msgs::handForceLevelResponse const> handForceLevelResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator1> & lhs, const ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.force_level == rhs.force_level;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator1> & lhs, const ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77e365aa913b429c04069f41b0a0fea7";
  }

  static const char* value(const ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77e365aa913b429cULL;
  static const uint64_t static_value2 = 0x04069f41b0a0fea7ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_msgs/handForceLevelResponse";
  }

  static const char* value(const ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"int8[] force_level\n"
;
  }

  static const char* value(const ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.force_level);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct handForceLevelResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_msgs::handForceLevelResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "force_level[]" << std::endl;
    for (size_t i = 0; i < v.force_level.size(); ++i)
    {
      s << indent << "  force_level[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.force_level[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_HANDFORCELEVELRESPONSE_H
