// Generated by gencpp from file kuavo_msgs/lejuClawCommand.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_LEJUCLAWCOMMAND_H
#define KUAVO_MSGS_MESSAGE_LEJUCLAWCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <kuavo_msgs/endEffectorData.h>

namespace kuavo_msgs
{
template <class ContainerAllocator>
struct lejuClawCommand_
{
  typedef lejuClawCommand_<ContainerAllocator> Type;

  lejuClawCommand_()
    : header()
    , data()  {
    }
  lejuClawCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::kuavo_msgs::endEffectorData_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> const> ConstPtr;

}; // struct lejuClawCommand_

typedef ::kuavo_msgs::lejuClawCommand_<std::allocator<void> > lejuClawCommand;

typedef boost::shared_ptr< ::kuavo_msgs::lejuClawCommand > lejuClawCommandPtr;
typedef boost::shared_ptr< ::kuavo_msgs::lejuClawCommand const> lejuClawCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_msgs::lejuClawCommand_<ContainerAllocator1> & lhs, const ::kuavo_msgs::lejuClawCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_msgs::lejuClawCommand_<ContainerAllocator1> & lhs, const ::kuavo_msgs::lejuClawCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57c40e80f90e7a289ae0b2488552e043";
  }

  static const char* value(const ::kuavo_msgs::lejuClawCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57c40e80f90e7a28ULL;
  static const uint64_t static_value2 = 0x9ae0b2488552e043ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_msgs/lejuClawCommand";
  }

  static const char* value(const ::kuavo_msgs::lejuClawCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# kuavo_msgs/endEffectorData:\n"
"# string[] name  \n"
"# float64[] position\n"
"# float64[] velocity  \n"
"# float64[] effort\n"
"# \n"
"# ** For the Topic Notes **\n"
"# \n"
"# name     : 'left_claw' , 'right_claw'\n"
"# position : 0 ~ 100, the percentage of the claw's opening angle\n"
"#            0: closed, 100: open   \n"
"# velocity : 0 ~ 100, if size is 0, will use default `50.0`.\n"
"# effort   : torque/current, better 1A ~ 2A, if size is 0, will use default `1.0`.\n"
"# \n"
"# ** Example **\n"
"# data:\n"
"#   - name: ['left_claw', 'right_claw']\n"
"#     position: [20.0, 20.0]\n"
"#     velocity: [50.0, 50.0]\n"
"#     effort: [1.0, 1.0]\n"
"\n"
"std_msgs/Header header\n"
"kuavo_msgs/endEffectorData data\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: kuavo_msgs/endEffectorData\n"
"string[] name  \n"
"float64[] position\n"
"float64[] velocity  \n"
"float64[] effort\n"
;
  }

  static const char* value(const ::kuavo_msgs::lejuClawCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lejuClawCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_msgs::lejuClawCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_msgs::lejuClawCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    s << std::endl;
    Printer< ::kuavo_msgs::endEffectorData_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_LEJUCLAWCOMMAND_H
