// Generated by gencpp from file kuavo_msgs/playmusic.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_PLAYMUSIC_H
#define KUAVO_MSGS_MESSAGE_PLAYMUSIC_H

#include <ros/service_traits.h>


#include <kuavo_msgs/playmusicRequest.h>
#include <kuavo_msgs/playmusicResponse.h>


namespace kuavo_msgs
{

struct playmusic
{

typedef playmusicRequest Request;
typedef playmusicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct playmusic
} // namespace kuavo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_msgs::playmusic > {
  static const char* value()
  {
    return "348f2445d1e569f5dc4e72a19fb11934";
  }

  static const char* value(const ::kuavo_msgs::playmusic&) { return value(); }
};

template<>
struct DataType< ::kuavo_msgs::playmusic > {
  static const char* value()
  {
    return "kuavo_msgs/playmusic";
  }

  static const char* value(const ::kuavo_msgs::playmusic&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_msgs::playmusicRequest> should match
// service_traits::MD5Sum< ::kuavo_msgs::playmusic >
template<>
struct MD5Sum< ::kuavo_msgs::playmusicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::playmusic >::value();
  }
  static const char* value(const ::kuavo_msgs::playmusicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::playmusicRequest> should match
// service_traits::DataType< ::kuavo_msgs::playmusic >
template<>
struct DataType< ::kuavo_msgs::playmusicRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::playmusic >::value();
  }
  static const char* value(const ::kuavo_msgs::playmusicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_msgs::playmusicResponse> should match
// service_traits::MD5Sum< ::kuavo_msgs::playmusic >
template<>
struct MD5Sum< ::kuavo_msgs::playmusicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::playmusic >::value();
  }
  static const char* value(const ::kuavo_msgs::playmusicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::playmusicResponse> should match
// service_traits::DataType< ::kuavo_msgs::playmusic >
template<>
struct DataType< ::kuavo_msgs::playmusicResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::playmusic >::value();
  }
  static const char* value(const ::kuavo_msgs::playmusicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_PLAYMUSIC_H
