// Generated by gencpp from file kuavo_msgs/setHwIntialState.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_SETHWINTIALSTATE_H
#define KUAVO_MSGS_MESSAGE_SETHWINTIALSTATE_H

#include <ros/service_traits.h>


#include <kuavo_msgs/setHwIntialStateRequest.h>
#include <kuavo_msgs/setHwIntialStateResponse.h>


namespace kuavo_msgs
{

struct setHwIntialState
{

typedef setHwIntialStateRequest Request;
typedef setHwIntialStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setHwIntialState
} // namespace kuavo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_msgs::setHwIntialState > {
  static const char* value()
  {
    return "5289a64acc27422c552070b8181b8118";
  }

  static const char* value(const ::kuavo_msgs::setHwIntialState&) { return value(); }
};

template<>
struct DataType< ::kuavo_msgs::setHwIntialState > {
  static const char* value()
  {
    return "kuavo_msgs/setHwIntialState";
  }

  static const char* value(const ::kuavo_msgs::setHwIntialState&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_msgs::setHwIntialStateRequest> should match
// service_traits::MD5Sum< ::kuavo_msgs::setHwIntialState >
template<>
struct MD5Sum< ::kuavo_msgs::setHwIntialStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::setHwIntialState >::value();
  }
  static const char* value(const ::kuavo_msgs::setHwIntialStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::setHwIntialStateRequest> should match
// service_traits::DataType< ::kuavo_msgs::setHwIntialState >
template<>
struct DataType< ::kuavo_msgs::setHwIntialStateRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::setHwIntialState >::value();
  }
  static const char* value(const ::kuavo_msgs::setHwIntialStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_msgs::setHwIntialStateResponse> should match
// service_traits::MD5Sum< ::kuavo_msgs::setHwIntialState >
template<>
struct MD5Sum< ::kuavo_msgs::setHwIntialStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::setHwIntialState >::value();
  }
  static const char* value(const ::kuavo_msgs::setHwIntialStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::setHwIntialStateResponse> should match
// service_traits::DataType< ::kuavo_msgs::setHwIntialState >
template<>
struct DataType< ::kuavo_msgs::setHwIntialStateResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::setHwIntialState >::value();
  }
  static const char* value(const ::kuavo_msgs::setHwIntialStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_SETHWINTIALSTATE_H
