// Generated by gencpp from file kuavo_msgs/setMotorEncoderRoundService.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_SETMOTORENCODERROUNDSERVICE_H
#define KUAVO_MSGS_MESSAGE_SETMOTORENCODERROUNDSERVICE_H

#include <ros/service_traits.h>


#include <kuavo_msgs/setMotorEncoderRoundServiceRequest.h>
#include <kuavo_msgs/setMotorEncoderRoundServiceResponse.h>


namespace kuavo_msgs
{

struct setMotorEncoderRoundService
{

typedef setMotorEncoderRoundServiceRequest Request;
typedef setMotorEncoderRoundServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setMotorEncoderRoundService
} // namespace kuavo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_msgs::setMotorEncoderRoundService > {
  static const char* value()
  {
    return "c8e2df10122ff9a180b403f54a3f8831";
  }

  static const char* value(const ::kuavo_msgs::setMotorEncoderRoundService&) { return value(); }
};

template<>
struct DataType< ::kuavo_msgs::setMotorEncoderRoundService > {
  static const char* value()
  {
    return "kuavo_msgs/setMotorEncoderRoundService";
  }

  static const char* value(const ::kuavo_msgs::setMotorEncoderRoundService&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_msgs::setMotorEncoderRoundServiceRequest> should match
// service_traits::MD5Sum< ::kuavo_msgs::setMotorEncoderRoundService >
template<>
struct MD5Sum< ::kuavo_msgs::setMotorEncoderRoundServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::setMotorEncoderRoundService >::value();
  }
  static const char* value(const ::kuavo_msgs::setMotorEncoderRoundServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::setMotorEncoderRoundServiceRequest> should match
// service_traits::DataType< ::kuavo_msgs::setMotorEncoderRoundService >
template<>
struct DataType< ::kuavo_msgs::setMotorEncoderRoundServiceRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::setMotorEncoderRoundService >::value();
  }
  static const char* value(const ::kuavo_msgs::setMotorEncoderRoundServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_msgs::setMotorEncoderRoundServiceResponse> should match
// service_traits::MD5Sum< ::kuavo_msgs::setMotorEncoderRoundService >
template<>
struct MD5Sum< ::kuavo_msgs::setMotorEncoderRoundServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::setMotorEncoderRoundService >::value();
  }
  static const char* value(const ::kuavo_msgs::setMotorEncoderRoundServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::setMotorEncoderRoundServiceResponse> should match
// service_traits::DataType< ::kuavo_msgs::setMotorEncoderRoundService >
template<>
struct DataType< ::kuavo_msgs::setMotorEncoderRoundServiceResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::setMotorEncoderRoundService >::value();
  }
  static const char* value(const ::kuavo_msgs::setMotorEncoderRoundServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_SETMOTORENCODERROUNDSERVICE_H
