// Generated by gencpp from file kuavo_msgs/setMmCtrlFrameRequest.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_SETMMCTRLFRAMEREQUEST_H
#define KUAVO_MSGS_MESSAGE_SETMMCTRLFRAMEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_msgs
{
template <class ContainerAllocator>
struct setMmCtrlFrameRequest_
{
  typedef setMmCtrlFrameRequest_<ContainerAllocator> Type;

  setMmCtrlFrameRequest_()
    : frame(0)  {
    }
  setMmCtrlFrameRequest_(const ContainerAllocator& _alloc)
    : frame(0)  {
  (void)_alloc;
    }



   typedef int32_t _frame_type;
  _frame_type frame;





  typedef boost::shared_ptr< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct setMmCtrlFrameRequest_

typedef ::kuavo_msgs::setMmCtrlFrameRequest_<std::allocator<void> > setMmCtrlFrameRequest;

typedef boost::shared_ptr< ::kuavo_msgs::setMmCtrlFrameRequest > setMmCtrlFrameRequestPtr;
typedef boost::shared_ptr< ::kuavo_msgs::setMmCtrlFrameRequest const> setMmCtrlFrameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator1> & lhs, const ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator2> & rhs)
{
  return lhs.frame == rhs.frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator1> & lhs, const ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e66db7b96bf089933dd98e52e1db8b7b";
  }

  static const char* value(const ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe66db7b96bf08993ULL;
  static const uint64_t static_value2 = 0x3dd98e52e1db8b7bULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_msgs/setMmCtrlFrameRequest";
  }

  static const char* value(const ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 frame\n"
;
  }

  static const char* value(const ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setMmCtrlFrameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_msgs::setMmCtrlFrameRequest_<ContainerAllocator>& v)
  {
    s << indent << "frame: ";
    Printer<int32_t>::stream(s, indent + "  ", v.frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_SETMMCTRLFRAMEREQUEST_H
