// Generated by gencpp from file kuavo_msgs/SetTagPose.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_SETTAGPOSE_H
#define KUAVO_MSGS_MESSAGE_SETTAGPOSE_H

#include <ros/service_traits.h>


#include <kuavo_msgs/SetTagPoseRequest.h>
#include <kuavo_msgs/SetTagPoseResponse.h>


namespace kuavo_msgs
{

struct SetTagPose
{

typedef SetTagPoseRequest Request;
typedef SetTagPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTagPose
} // namespace kuavo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_msgs::SetTagPose > {
  static const char* value()
  {
    return "04a66d62173ddb0945f89d9279dd4ddb";
  }

  static const char* value(const ::kuavo_msgs::SetTagPose&) { return value(); }
};

template<>
struct DataType< ::kuavo_msgs::SetTagPose > {
  static const char* value()
  {
    return "kuavo_msgs/SetTagPose";
  }

  static const char* value(const ::kuavo_msgs::SetTagPose&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_msgs::SetTagPoseRequest> should match
// service_traits::MD5Sum< ::kuavo_msgs::SetTagPose >
template<>
struct MD5Sum< ::kuavo_msgs::SetTagPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::SetTagPose >::value();
  }
  static const char* value(const ::kuavo_msgs::SetTagPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::SetTagPoseRequest> should match
// service_traits::DataType< ::kuavo_msgs::SetTagPose >
template<>
struct DataType< ::kuavo_msgs::SetTagPoseRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::SetTagPose >::value();
  }
  static const char* value(const ::kuavo_msgs::SetTagPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_msgs::SetTagPoseResponse> should match
// service_traits::MD5Sum< ::kuavo_msgs::SetTagPose >
template<>
struct MD5Sum< ::kuavo_msgs::SetTagPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::SetTagPose >::value();
  }
  static const char* value(const ::kuavo_msgs::SetTagPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::SetTagPoseResponse> should match
// service_traits::DataType< ::kuavo_msgs::SetTagPose >
template<>
struct DataType< ::kuavo_msgs::SetTagPoseResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::SetTagPose >::value();
  }
  static const char* value(const ::kuavo_msgs::SetTagPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_SETTAGPOSE_H
