// Generated by gencpp from file kuavo_msgs/setTagIdRequest.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_SETTAGIDREQUEST_H
#define KUAVO_MSGS_MESSAGE_SETTAGIDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_msgs
{
template <class ContainerAllocator>
struct setTagIdRequest_
{
  typedef setTagIdRequest_<ContainerAllocator> Type;

  setTagIdRequest_()
    : tag_id(0)  {
    }
  setTagIdRequest_(const ContainerAllocator& _alloc)
    : tag_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _tag_id_type;
  _tag_id_type tag_id;





  typedef boost::shared_ptr< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct setTagIdRequest_

typedef ::kuavo_msgs::setTagIdRequest_<std::allocator<void> > setTagIdRequest;

typedef boost::shared_ptr< ::kuavo_msgs::setTagIdRequest > setTagIdRequestPtr;
typedef boost::shared_ptr< ::kuavo_msgs::setTagIdRequest const> setTagIdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_msgs::setTagIdRequest_<ContainerAllocator1> & lhs, const ::kuavo_msgs::setTagIdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.tag_id == rhs.tag_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_msgs::setTagIdRequest_<ContainerAllocator1> & lhs, const ::kuavo_msgs::setTagIdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ab0b8b553a9751c72d3d7cbe44c28ff";
  }

  static const char* value(const ::kuavo_msgs::setTagIdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ab0b8b553a9751cULL;
  static const uint64_t static_value2 = 0x72d3d7cbe44c28ffULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_msgs/setTagIdRequest";
  }

  static const char* value(const ::kuavo_msgs::setTagIdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 tag_id \n"
;
  }

  static const char* value(const ::kuavo_msgs::setTagIdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tag_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setTagIdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_msgs::setTagIdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_msgs::setTagIdRequest_<ContainerAllocator>& v)
  {
    s << indent << "tag_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tag_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_SETTAGIDREQUEST_H
