// Generated by gencpp from file kuavo_msgs/singleStepControl.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_SINGLESTEPCONTROL_H
#define KUAVO_MSGS_MESSAGE_SINGLESTEPCONTROL_H

#include <ros/service_traits.h>


#include <kuavo_msgs/singleStepControlRequest.h>
#include <kuavo_msgs/singleStepControlResponse.h>


namespace kuavo_msgs
{

struct singleStepControl
{

typedef singleStepControlRequest Request;
typedef singleStepControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct singleStepControl
} // namespace kuavo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_msgs::singleStepControl > {
  static const char* value()
  {
    return "9a5a8ad57a17963a16bf197fc7a66fa4";
  }

  static const char* value(const ::kuavo_msgs::singleStepControl&) { return value(); }
};

template<>
struct DataType< ::kuavo_msgs::singleStepControl > {
  static const char* value()
  {
    return "kuavo_msgs/singleStepControl";
  }

  static const char* value(const ::kuavo_msgs::singleStepControl&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_msgs::singleStepControlRequest> should match
// service_traits::MD5Sum< ::kuavo_msgs::singleStepControl >
template<>
struct MD5Sum< ::kuavo_msgs::singleStepControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::singleStepControl >::value();
  }
  static const char* value(const ::kuavo_msgs::singleStepControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::singleStepControlRequest> should match
// service_traits::DataType< ::kuavo_msgs::singleStepControl >
template<>
struct DataType< ::kuavo_msgs::singleStepControlRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::singleStepControl >::value();
  }
  static const char* value(const ::kuavo_msgs::singleStepControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_msgs::singleStepControlResponse> should match
// service_traits::MD5Sum< ::kuavo_msgs::singleStepControl >
template<>
struct MD5Sum< ::kuavo_msgs::singleStepControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::singleStepControl >::value();
  }
  static const char* value(const ::kuavo_msgs::singleStepControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::singleStepControlResponse> should match
// service_traits::DataType< ::kuavo_msgs::singleStepControl >
template<>
struct DataType< ::kuavo_msgs::singleStepControlResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::singleStepControl >::value();
  }
  static const char* value(const ::kuavo_msgs::singleStepControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_SINGLESTEPCONTROL_H
