// Generated by gencpp from file kuavo_msgs/SpeechSynthesis.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_SPEECHSYNTHESIS_H
#define KUAVO_MSGS_MESSAGE_SPEECHSYNTHESIS_H

#include <ros/service_traits.h>


#include <kuavo_msgs/SpeechSynthesisRequest.h>
#include <kuavo_msgs/SpeechSynthesisResponse.h>


namespace kuavo_msgs
{

struct SpeechSynthesis
{

typedef SpeechSynthesisRequest Request;
typedef SpeechSynthesisResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpeechSynthesis
} // namespace kuavo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_msgs::SpeechSynthesis > {
  static const char* value()
  {
    return "c2d03ac0ff2ddd1cb86a5148ad0f9d5e";
  }

  static const char* value(const ::kuavo_msgs::SpeechSynthesis&) { return value(); }
};

template<>
struct DataType< ::kuavo_msgs::SpeechSynthesis > {
  static const char* value()
  {
    return "kuavo_msgs/SpeechSynthesis";
  }

  static const char* value(const ::kuavo_msgs::SpeechSynthesis&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_msgs::SpeechSynthesisRequest> should match
// service_traits::MD5Sum< ::kuavo_msgs::SpeechSynthesis >
template<>
struct MD5Sum< ::kuavo_msgs::SpeechSynthesisRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::SpeechSynthesis >::value();
  }
  static const char* value(const ::kuavo_msgs::SpeechSynthesisRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::SpeechSynthesisRequest> should match
// service_traits::DataType< ::kuavo_msgs::SpeechSynthesis >
template<>
struct DataType< ::kuavo_msgs::SpeechSynthesisRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::SpeechSynthesis >::value();
  }
  static const char* value(const ::kuavo_msgs::SpeechSynthesisRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_msgs::SpeechSynthesisResponse> should match
// service_traits::MD5Sum< ::kuavo_msgs::SpeechSynthesis >
template<>
struct MD5Sum< ::kuavo_msgs::SpeechSynthesisResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::SpeechSynthesis >::value();
  }
  static const char* value(const ::kuavo_msgs::SpeechSynthesisResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::SpeechSynthesisResponse> should match
// service_traits::DataType< ::kuavo_msgs::SpeechSynthesis >
template<>
struct DataType< ::kuavo_msgs::SpeechSynthesisResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::SpeechSynthesis >::value();
  }
  static const char* value(const ::kuavo_msgs::SpeechSynthesisResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_SPEECHSYNTHESIS_H
