// Generated by gencpp from file kuavo_msgs/SpeechSynthesisRequest.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_SPEECHSYNTHESISREQUEST_H
#define KUAVO_MSGS_MESSAGE_SPEECHSYNTHESISREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_msgs
{
template <class ContainerAllocator>
struct SpeechSynthesisRequest_
{
  typedef SpeechSynthesisRequest_<ContainerAllocator> Type;

  SpeechSynthesisRequest_()
    : data()
    , volume(0.0)  {
    }
  SpeechSynthesisRequest_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , volume(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;

   typedef float _volume_type;
  _volume_type volume;





  typedef boost::shared_ptr< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechSynthesisRequest_

typedef ::kuavo_msgs::SpeechSynthesisRequest_<std::allocator<void> > SpeechSynthesisRequest;

typedef boost::shared_ptr< ::kuavo_msgs::SpeechSynthesisRequest > SpeechSynthesisRequestPtr;
typedef boost::shared_ptr< ::kuavo_msgs::SpeechSynthesisRequest const> SpeechSynthesisRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator1> & lhs, const ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.volume == rhs.volume;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator1> & lhs, const ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32375f7a1df36dcb2da804a90b1edd81";
  }

  static const char* value(const ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32375f7a1df36dcbULL;
  static const uint64_t static_value2 = 0x2da804a90b1edd81ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_msgs/SpeechSynthesisRequest";
  }

  static const char* value(const ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 请求部分\n"
"string data\n"
"float32 volume\n"
;
  }

  static const char* value(const ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.volume);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechSynthesisRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_msgs::SpeechSynthesisRequest_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
    s << indent << "volume: ";
    Printer<float>::stream(s, indent + "  ", v.volume);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_SPEECHSYNTHESISREQUEST_H
