// Generated by gencpp from file kuavo_msgs/twoArmHandPoseCmdSrv.msg
// DO NOT EDIT!


#ifndef KUAVO_MSGS_MESSAGE_TWOARMHANDPOSECMDSRV_H
#define KUAVO_MSGS_MESSAGE_TWOARMHANDPOSECMDSRV_H

#include <ros/service_traits.h>


#include <kuavo_msgs/twoArmHandPoseCmdSrvRequest.h>
#include <kuavo_msgs/twoArmHandPoseCmdSrvResponse.h>


namespace kuavo_msgs
{

struct twoArmHandPoseCmdSrv
{

typedef twoArmHandPoseCmdSrvRequest Request;
typedef twoArmHandPoseCmdSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct twoArmHandPoseCmdSrv
} // namespace kuavo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_msgs::twoArmHandPoseCmdSrv > {
  static const char* value()
  {
    return "5c40c421651b828448c8e8f1a4ba5e3d";
  }

  static const char* value(const ::kuavo_msgs::twoArmHandPoseCmdSrv&) { return value(); }
};

template<>
struct DataType< ::kuavo_msgs::twoArmHandPoseCmdSrv > {
  static const char* value()
  {
    return "kuavo_msgs/twoArmHandPoseCmdSrv";
  }

  static const char* value(const ::kuavo_msgs::twoArmHandPoseCmdSrv&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_msgs::twoArmHandPoseCmdSrvRequest> should match
// service_traits::MD5Sum< ::kuavo_msgs::twoArmHandPoseCmdSrv >
template<>
struct MD5Sum< ::kuavo_msgs::twoArmHandPoseCmdSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::twoArmHandPoseCmdSrv >::value();
  }
  static const char* value(const ::kuavo_msgs::twoArmHandPoseCmdSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::twoArmHandPoseCmdSrvRequest> should match
// service_traits::DataType< ::kuavo_msgs::twoArmHandPoseCmdSrv >
template<>
struct DataType< ::kuavo_msgs::twoArmHandPoseCmdSrvRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::twoArmHandPoseCmdSrv >::value();
  }
  static const char* value(const ::kuavo_msgs::twoArmHandPoseCmdSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_msgs::twoArmHandPoseCmdSrvResponse> should match
// service_traits::MD5Sum< ::kuavo_msgs::twoArmHandPoseCmdSrv >
template<>
struct MD5Sum< ::kuavo_msgs::twoArmHandPoseCmdSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_msgs::twoArmHandPoseCmdSrv >::value();
  }
  static const char* value(const ::kuavo_msgs::twoArmHandPoseCmdSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_msgs::twoArmHandPoseCmdSrvResponse> should match
// service_traits::DataType< ::kuavo_msgs::twoArmHandPoseCmdSrv >
template<>
struct DataType< ::kuavo_msgs::twoArmHandPoseCmdSrvResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_msgs::twoArmHandPoseCmdSrv >::value();
  }
  static const char* value(const ::kuavo_msgs::twoArmHandPoseCmdSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_MSGS_MESSAGE_TWOARMHANDPOSECMDSRV_H
