(cl:in-package kuavo_msgs-msg)
(cl:export '(MAJOR_OPTIMALITY_TOL-VAL
          MAJOR_OPTIMALITY_TOL
          MAJOR_FEASIBILITY_TOL-VAL
          MAJOR_FEASIBILITY_TOL
          MINOR_FEASIBILITY_TOL-VAL
          MINOR_FEASIBILITY_TOL
          MAJOR_ITERATIONS_LIMIT-VAL
          MAJOR_ITERATIONS_LIMIT
          ORITATION_CONSTRAINT_TOL-VAL
          ORITATION_CONSTRAINT_TOL
          POS_CONSTRAINT_TOL-VAL
          POS_CONSTRAINT_TOL
          POS_COST_WEIGHT-VAL
          POS_COST_WEIGHT
))