(cl:in-package kuavo_msgs-msg)
(cl:export '(NORMAL_FORCE1-VAL
          NORMAL_FORCE1
          NORMAL_FORCE2-VAL
          NORMAL_FORCE2
          NORMAL_FORCE3-VAL
          NORMAL_FORCE3
          TANGENTIAL_FORCE1-VAL
          TANGENTIAL_FORCE1
          TANGENTIAL_FORCE2-VAL
          TANGENTIAL_FORCE2
          TANGENTIAL_FORCE3-VAL
          TANGENTIAL_FORCE3
          TANGENTIAL_DIRECTION1-VAL
          TANGENTIAL_DIRECTION1
          TANGENTIAL_DIRECTION2-VAL
          TANGENTIAL_DIRECTION2
          TANGENTIAL_DIRECTION3-VAL
          TANGENTIAL_DIRECTION3
          SELF_PROXIMITY1-VAL
          SELF_PROXIMITY1
          SELF_PROXIMITY2-VAL
          SELF_PROXIMITY2
          MUTUAL_PROXIMITY-VAL
          MUTUAL_PROXIMITY
          STATUS-VAL
          STATUS
))