// Generated by gencpp from file motion_capture_ik/changeArmCtrlModeKuavoRequest.msg
// DO NOT EDIT!


#ifndef MOTION_CAPTURE_IK_MESSAGE_CHANGEARMCTRLMODEKUAVOREQUEST_H
#define MOTION_CAPTURE_IK_MESSAGE_CHANGEARMCTRLMODEKUAVOREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_capture_ik
{
template <class ContainerAllocator>
struct changeArmCtrlModeKuavoRequest_
{
  typedef changeArmCtrlModeKuavoRequest_<ContainerAllocator> Type;

  changeArmCtrlModeKuavoRequest_()
    : control_mode(false)  {
    }
  changeArmCtrlModeKuavoRequest_(const ContainerAllocator& _alloc)
    : control_mode(false)  {
  (void)_alloc;
    }



   typedef uint8_t _control_mode_type;
  _control_mode_type control_mode;





  typedef boost::shared_ptr< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct changeArmCtrlModeKuavoRequest_

typedef ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<std::allocator<void> > changeArmCtrlModeKuavoRequest;

typedef boost::shared_ptr< ::motion_capture_ik::changeArmCtrlModeKuavoRequest > changeArmCtrlModeKuavoRequestPtr;
typedef boost::shared_ptr< ::motion_capture_ik::changeArmCtrlModeKuavoRequest const> changeArmCtrlModeKuavoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator1> & lhs, const ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.control_mode == rhs.control_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator1> & lhs, const ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_capture_ik

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14ef2aa2f48bb3f617c9e71fd0bc444e";
  }

  static const char* value(const ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14ef2aa2f48bb3f6ULL;
  static const uint64_t static_value2 = 0x17c9e71fd0bc444eULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_capture_ik/changeArmCtrlModeKuavoRequest";
  }

  static const char* value(const ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool control_mode\n"
;
  }

  static const char* value(const ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct changeArmCtrlModeKuavoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_capture_ik::changeArmCtrlModeKuavoRequest_<ContainerAllocator>& v)
  {
    s << indent << "control_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_CAPTURE_IK_MESSAGE_CHANGEARMCTRLMODEKUAVOREQUEST_H
