// Generated by gencpp from file motion_capture_ik/changeArmCtrlModeKuavoResponse.msg
// DO NOT EDIT!


#ifndef MOTION_CAPTURE_IK_MESSAGE_CHANGEARMCTRLMODEKUAVORESPONSE_H
#define MOTION_CAPTURE_IK_MESSAGE_CHANGEARMCTRLMODEKUAVORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_capture_ik
{
template <class ContainerAllocator>
struct changeArmCtrlModeKuavoResponse_
{
  typedef changeArmCtrlModeKuavoResponse_<ContainerAllocator> Type;

  changeArmCtrlModeKuavoResponse_()
    : result(false)  {
    }
  changeArmCtrlModeKuavoResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct changeArmCtrlModeKuavoResponse_

typedef ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<std::allocator<void> > changeArmCtrlModeKuavoResponse;

typedef boost::shared_ptr< ::motion_capture_ik::changeArmCtrlModeKuavoResponse > changeArmCtrlModeKuavoResponsePtr;
typedef boost::shared_ptr< ::motion_capture_ik::changeArmCtrlModeKuavoResponse const> changeArmCtrlModeKuavoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator1> & lhs, const ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator1> & lhs, const ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_capture_ik

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_capture_ik/changeArmCtrlModeKuavoResponse";
  }

  static const char* value(const ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
"\n"
;
  }

  static const char* value(const ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct changeArmCtrlModeKuavoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_capture_ik::changeArmCtrlModeKuavoResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_CAPTURE_IK_MESSAGE_CHANGEARMCTRLMODEKUAVORESPONSE_H
