// Generated by gencpp from file motion_capture_ik/fkSrv.msg
// DO NOT EDIT!


#ifndef MOTION_CAPTURE_IK_MESSAGE_FKSRV_H
#define MOTION_CAPTURE_IK_MESSAGE_FKSRV_H

#include <ros/service_traits.h>


#include <motion_capture_ik/fkSrvRequest.h>
#include <motion_capture_ik/fkSrvResponse.h>


namespace motion_capture_ik
{

struct fkSrv
{

typedef fkSrvRequest Request;
typedef fkSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct fkSrv
} // namespace motion_capture_ik


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::motion_capture_ik::fkSrv > {
  static const char* value()
  {
    return "b89cc987a02b6d1c2a1588d5659bf064";
  }

  static const char* value(const ::motion_capture_ik::fkSrv&) { return value(); }
};

template<>
struct DataType< ::motion_capture_ik::fkSrv > {
  static const char* value()
  {
    return "motion_capture_ik/fkSrv";
  }

  static const char* value(const ::motion_capture_ik::fkSrv&) { return value(); }
};


// service_traits::MD5Sum< ::motion_capture_ik::fkSrvRequest> should match
// service_traits::MD5Sum< ::motion_capture_ik::fkSrv >
template<>
struct MD5Sum< ::motion_capture_ik::fkSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::motion_capture_ik::fkSrv >::value();
  }
  static const char* value(const ::motion_capture_ik::fkSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_capture_ik::fkSrvRequest> should match
// service_traits::DataType< ::motion_capture_ik::fkSrv >
template<>
struct DataType< ::motion_capture_ik::fkSrvRequest>
{
  static const char* value()
  {
    return DataType< ::motion_capture_ik::fkSrv >::value();
  }
  static const char* value(const ::motion_capture_ik::fkSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::motion_capture_ik::fkSrvResponse> should match
// service_traits::MD5Sum< ::motion_capture_ik::fkSrv >
template<>
struct MD5Sum< ::motion_capture_ik::fkSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::motion_capture_ik::fkSrv >::value();
  }
  static const char* value(const ::motion_capture_ik::fkSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::motion_capture_ik::fkSrvResponse> should match
// service_traits::DataType< ::motion_capture_ik::fkSrv >
template<>
struct DataType< ::motion_capture_ik::fkSrvResponse>
{
  static const char* value()
  {
    return DataType< ::motion_capture_ik::fkSrv >::value();
  }
  static const char* value(const ::motion_capture_ik::fkSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOTION_CAPTURE_IK_MESSAGE_FKSRV_H
