// Generated by gencpp from file motion_capture_ik/fkSrvRequest.msg
// DO NOT EDIT!


#ifndef MOTION_CAPTURE_IK_MESSAGE_FKSRVREQUEST_H
#define MOTION_CAPTURE_IK_MESSAGE_FKSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motion_capture_ik
{
template <class ContainerAllocator>
struct fkSrvRequest_
{
  typedef fkSrvRequest_<ContainerAllocator> Type;

  fkSrvRequest_()
    : q()  {
    }
  fkSrvRequest_(const ContainerAllocator& _alloc)
    : q(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _q_type;
  _q_type q;





  typedef boost::shared_ptr< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct fkSrvRequest_

typedef ::motion_capture_ik::fkSrvRequest_<std::allocator<void> > fkSrvRequest;

typedef boost::shared_ptr< ::motion_capture_ik::fkSrvRequest > fkSrvRequestPtr;
typedef boost::shared_ptr< ::motion_capture_ik::fkSrvRequest const> fkSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_capture_ik::fkSrvRequest_<ContainerAllocator1> & lhs, const ::motion_capture_ik::fkSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.q == rhs.q;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_capture_ik::fkSrvRequest_<ContainerAllocator1> & lhs, const ::motion_capture_ik::fkSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_capture_ik

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab94b9bcaaa12f74def43e4b33992df1";
  }

  static const char* value(const ::motion_capture_ik::fkSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab94b9bcaaa12f74ULL;
  static const uint64_t static_value2 = 0xdef43e4b33992df1ULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_capture_ik/fkSrvRequest";
  }

  static const char* value(const ::motion_capture_ik::fkSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] q # 广义关节角度，如果是虚拟关节ik，则前4维度为躯干虚拟关节的角度，后14维度为手臂关节的角度\n"
;
  }

  static const char* value(const ::motion_capture_ik::fkSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fkSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_capture_ik::fkSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_capture_ik::fkSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "q[]" << std::endl;
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      s << indent << "  q[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.q[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_CAPTURE_IK_MESSAGE_FKSRVREQUEST_H
