// Generated by gencpp from file motion_capture_ik/twoArmHandPose.msg
// DO NOT EDIT!


#ifndef MOTION_CAPTURE_IK_MESSAGE_TWOARMHANDPOSE_H
#define MOTION_CAPTURE_IK_MESSAGE_TWOARMHANDPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <motion_capture_ik/armHandPose.h>
#include <motion_capture_ik/armHandPose.h>

namespace motion_capture_ik
{
template <class ContainerAllocator>
struct twoArmHandPose_
{
  typedef twoArmHandPose_<ContainerAllocator> Type;

  twoArmHandPose_()
    : header()
    , left_pose()
    , right_pose()  {
    }
  twoArmHandPose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left_pose(_alloc)
    , right_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::motion_capture_ik::armHandPose_<ContainerAllocator>  _left_pose_type;
  _left_pose_type left_pose;

   typedef  ::motion_capture_ik::armHandPose_<ContainerAllocator>  _right_pose_type;
  _right_pose_type right_pose;





  typedef boost::shared_ptr< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> const> ConstPtr;

}; // struct twoArmHandPose_

typedef ::motion_capture_ik::twoArmHandPose_<std::allocator<void> > twoArmHandPose;

typedef boost::shared_ptr< ::motion_capture_ik::twoArmHandPose > twoArmHandPosePtr;
typedef boost::shared_ptr< ::motion_capture_ik::twoArmHandPose const> twoArmHandPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motion_capture_ik::twoArmHandPose_<ContainerAllocator1> & lhs, const ::motion_capture_ik::twoArmHandPose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left_pose == rhs.left_pose &&
    lhs.right_pose == rhs.right_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motion_capture_ik::twoArmHandPose_<ContainerAllocator1> & lhs, const ::motion_capture_ik::twoArmHandPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motion_capture_ik

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bdb1e027f430369b6f88e5e2f5d31ca";
  }

  static const char* value(const ::motion_capture_ik::twoArmHandPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bdb1e027f430369ULL;
  static const uint64_t static_value2 = 0xb6f88e5e2f5d31caULL;
};

template<class ContainerAllocator>
struct DataType< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motion_capture_ik/twoArmHandPose";
  }

  static const char* value(const ::motion_capture_ik::twoArmHandPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"armHandPose  left_pose\n"
"armHandPose  right_pose\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: motion_capture_ik/armHandPose\n"
"float64[3] pos_xyz\n"
"float64[4] quat_xyzw\n"
"\n"
"float64[3] elbow_pos_xyz\n"
"\n"
"float64[7] joint_angles\n"
;
  }

  static const char* value(const ::motion_capture_ik::twoArmHandPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left_pose);
      stream.next(m.right_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct twoArmHandPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motion_capture_ik::twoArmHandPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motion_capture_ik::twoArmHandPose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left_pose: ";
    s << std::endl;
    Printer< ::motion_capture_ik::armHandPose_<ContainerAllocator> >::stream(s, indent + "  ", v.left_pose);
    s << indent << "right_pose: ";
    s << std::endl;
    Printer< ::motion_capture_ik::armHandPose_<ContainerAllocator> >::stream(s, indent + "  ", v.right_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTION_CAPTURE_IK_MESSAGE_TWOARMHANDPOSE_H
