(cl:defpackage kuavo_ros_interfaces-msg
  (:use )
  (:export
   "<ARMTARGETPOSES>"
   "ARMTARGETPOSES"
   "<BEZIERCURVECUBICPOINT>"
   "BEZIERCURVECUBICPOINT"
   "<JOINTBEZIERTRAJECTORY>"
   "JOINTBEZIERTRAJECTORY"
   "<PLANARMSTATE>"
   "PLANARMSTATE"
   "<ROBOTHANDPOSITION>"
   "ROBOTHANDPOSITION"
   "<ROBOTHEADMOTIONDATA>"
   "ROBOTHEADMOTIONDATA"
  ))

