; Auto-generated. Do not edit!


(cl:in-package kuavo_ros_interfaces-msg)


;//! \htmlinclude bezierCurveCubicPoint.msg.html

(cl:defclass <bezierCurveCubicPoint> (roslisp-msg-protocol:ros-message)
  ((end_point
    :reader end_point
    :initarg :end_point
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (left_control_point
    :reader left_control_point
    :initarg :left_control_point
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (right_control_point
    :reader right_control_point
    :initarg :right_control_point
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass bezierCurveCubicPoint (<bezierCurveCubicPoint>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <bezierCurveCubicPoint>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'bezierCurveCubicPoint)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name kuavo_ros_interfaces-msg:<bezierCurveCubicPoint> is deprecated: use kuavo_ros_interfaces-msg:bezierCurveCubicPoint instead.")))

(cl:ensure-generic-function 'end_point-val :lambda-list '(m))
(cl:defmethod end_point-val ((m <bezierCurveCubicPoint>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kuavo_ros_interfaces-msg:end_point-val is deprecated.  Use kuavo_ros_interfaces-msg:end_point instead.")
  (end_point m))

(cl:ensure-generic-function 'left_control_point-val :lambda-list '(m))
(cl:defmethod left_control_point-val ((m <bezierCurveCubicPoint>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kuavo_ros_interfaces-msg:left_control_point-val is deprecated.  Use kuavo_ros_interfaces-msg:left_control_point instead.")
  (left_control_point m))

(cl:ensure-generic-function 'right_control_point-val :lambda-list '(m))
(cl:defmethod right_control_point-val ((m <bezierCurveCubicPoint>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader kuavo_ros_interfaces-msg:right_control_point-val is deprecated.  Use kuavo_ros_interfaces-msg:right_control_point instead.")
  (right_control_point m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <bezierCurveCubicPoint>) ostream)
  "Serializes a message object of type '<bezierCurveCubicPoint>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'end_point))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'end_point))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'left_control_point))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'left_control_point))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'right_control_point))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'right_control_point))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <bezierCurveCubicPoint>) istream)
  "Deserializes a message object of type '<bezierCurveCubicPoint>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'end_point) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'end_point)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'left_control_point) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'left_control_point)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'right_control_point) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'right_control_point)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<bezierCurveCubicPoint>)))
  "Returns string type for a message object of type '<bezierCurveCubicPoint>"
  "kuavo_ros_interfaces/bezierCurveCubicPoint")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'bezierCurveCubicPoint)))
  "Returns string type for a message object of type 'bezierCurveCubicPoint"
  "kuavo_ros_interfaces/bezierCurveCubicPoint")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<bezierCurveCubicPoint>)))
  "Returns md5sum for a message object of type '<bezierCurveCubicPoint>"
  "4262726b7e41e02a58fb5df3475aa027")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'bezierCurveCubicPoint)))
  "Returns md5sum for a message object of type 'bezierCurveCubicPoint"
  "4262726b7e41e02a58fb5df3475aa027")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<bezierCurveCubicPoint>)))
  "Returns full string definition for message of type '<bezierCurveCubicPoint>"
  (cl:format cl:nil "# [x, y] x is time, y is value~%~%float64[] end_point~%float64[] left_control_point~%float64[] right_control_point~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'bezierCurveCubicPoint)))
  "Returns full string definition for message of type 'bezierCurveCubicPoint"
  (cl:format cl:nil "# [x, y] x is time, y is value~%~%float64[] end_point~%float64[] left_control_point~%float64[] right_control_point~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <bezierCurveCubicPoint>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'end_point) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'left_control_point) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'right_control_point) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <bezierCurveCubicPoint>))
  "Converts a ROS message object to a list"
  (cl:list 'bezierCurveCubicPoint
    (cl:cons ':end_point (end_point msg))
    (cl:cons ':left_control_point (left_control_point msg))
    (cl:cons ':right_control_point (right_control_point msg))
))
