// Generated by gencpp from file h12pro_controller_node/changeArmCtrlMode.msg
// DO NOT EDIT!


#ifndef H12PRO_CONTROLLER_NODE_MESSAGE_CHANGEARMCTRLMODE_H
#define H12PRO_CONTROLLER_NODE_MESSAGE_CHANGEARMCTRLMODE_H

#include <ros/service_traits.h>


#include <h12pro_controller_node/changeArmCtrlModeRequest.h>
#include <h12pro_controller_node/changeArmCtrlModeResponse.h>


namespace h12pro_controller_node
{

struct changeArmCtrlMode
{

typedef changeArmCtrlModeRequest Request;
typedef changeArmCtrlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct changeArmCtrlMode
} // namespace h12pro_controller_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::h12pro_controller_node::changeArmCtrlMode > {
  static const char* value()
  {
    return "f89438f9d6f48f748eabe64775a22261";
  }

  static const char* value(const ::h12pro_controller_node::changeArmCtrlMode&) { return value(); }
};

template<>
struct DataType< ::h12pro_controller_node::changeArmCtrlMode > {
  static const char* value()
  {
    return "h12pro_controller_node/changeArmCtrlMode";
  }

  static const char* value(const ::h12pro_controller_node::changeArmCtrlMode&) { return value(); }
};


// service_traits::MD5Sum< ::h12pro_controller_node::changeArmCtrlModeRequest> should match
// service_traits::MD5Sum< ::h12pro_controller_node::changeArmCtrlMode >
template<>
struct MD5Sum< ::h12pro_controller_node::changeArmCtrlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::h12pro_controller_node::changeArmCtrlMode >::value();
  }
  static const char* value(const ::h12pro_controller_node::changeArmCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::h12pro_controller_node::changeArmCtrlModeRequest> should match
// service_traits::DataType< ::h12pro_controller_node::changeArmCtrlMode >
template<>
struct DataType< ::h12pro_controller_node::changeArmCtrlModeRequest>
{
  static const char* value()
  {
    return DataType< ::h12pro_controller_node::changeArmCtrlMode >::value();
  }
  static const char* value(const ::h12pro_controller_node::changeArmCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::h12pro_controller_node::changeArmCtrlModeResponse> should match
// service_traits::MD5Sum< ::h12pro_controller_node::changeArmCtrlMode >
template<>
struct MD5Sum< ::h12pro_controller_node::changeArmCtrlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::h12pro_controller_node::changeArmCtrlMode >::value();
  }
  static const char* value(const ::h12pro_controller_node::changeArmCtrlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::h12pro_controller_node::changeArmCtrlModeResponse> should match
// service_traits::DataType< ::h12pro_controller_node::changeArmCtrlMode >
template<>
struct DataType< ::h12pro_controller_node::changeArmCtrlModeResponse>
{
  static const char* value()
  {
    return DataType< ::h12pro_controller_node::changeArmCtrlMode >::value();
  }
  static const char* value(const ::h12pro_controller_node::changeArmCtrlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // H12PRO_CONTROLLER_NODE_MESSAGE_CHANGEARMCTRLMODE_H
