// Generated by gencpp from file h12pro_controller_node/changeHandArmPosesByConfigName.msg
// DO NOT EDIT!


#ifndef H12PRO_CONTROLLER_NODE_MESSAGE_CHANGEHANDARMPOSESBYCONFIGNAME_H
#define H12PRO_CONTROLLER_NODE_MESSAGE_CHANGEHANDARMPOSESBYCONFIGNAME_H

#include <ros/service_traits.h>


#include <h12pro_controller_node/changeHandArmPosesByConfigNameRequest.h>
#include <h12pro_controller_node/changeHandArmPosesByConfigNameResponse.h>


namespace h12pro_controller_node
{

struct changeHandArmPosesByConfigName
{

typedef changeHandArmPosesByConfigNameRequest Request;
typedef changeHandArmPosesByConfigNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct changeHandArmPosesByConfigName
} // namespace h12pro_controller_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::h12pro_controller_node::changeHandArmPosesByConfigName > {
  static const char* value()
  {
    return "981617b9cc6699ade1d3c011b67988a7";
  }

  static const char* value(const ::h12pro_controller_node::changeHandArmPosesByConfigName&) { return value(); }
};

template<>
struct DataType< ::h12pro_controller_node::changeHandArmPosesByConfigName > {
  static const char* value()
  {
    return "h12pro_controller_node/changeHandArmPosesByConfigName";
  }

  static const char* value(const ::h12pro_controller_node::changeHandArmPosesByConfigName&) { return value(); }
};


// service_traits::MD5Sum< ::h12pro_controller_node::changeHandArmPosesByConfigNameRequest> should match
// service_traits::MD5Sum< ::h12pro_controller_node::changeHandArmPosesByConfigName >
template<>
struct MD5Sum< ::h12pro_controller_node::changeHandArmPosesByConfigNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::h12pro_controller_node::changeHandArmPosesByConfigName >::value();
  }
  static const char* value(const ::h12pro_controller_node::changeHandArmPosesByConfigNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::h12pro_controller_node::changeHandArmPosesByConfigNameRequest> should match
// service_traits::DataType< ::h12pro_controller_node::changeHandArmPosesByConfigName >
template<>
struct DataType< ::h12pro_controller_node::changeHandArmPosesByConfigNameRequest>
{
  static const char* value()
  {
    return DataType< ::h12pro_controller_node::changeHandArmPosesByConfigName >::value();
  }
  static const char* value(const ::h12pro_controller_node::changeHandArmPosesByConfigNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse> should match
// service_traits::MD5Sum< ::h12pro_controller_node::changeHandArmPosesByConfigName >
template<>
struct MD5Sum< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::h12pro_controller_node::changeHandArmPosesByConfigName >::value();
  }
  static const char* value(const ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse> should match
// service_traits::DataType< ::h12pro_controller_node::changeHandArmPosesByConfigName >
template<>
struct DataType< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse>
{
  static const char* value()
  {
    return DataType< ::h12pro_controller_node::changeHandArmPosesByConfigName >::value();
  }
  static const char* value(const ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // H12PRO_CONTROLLER_NODE_MESSAGE_CHANGEHANDARMPOSESBYCONFIGNAME_H
