// Generated by gencpp from file h12pro_controller_node/changeHandArmPosesByConfigNameResponse.msg
// DO NOT EDIT!


#ifndef H12PRO_CONTROLLER_NODE_MESSAGE_CHANGEHANDARMPOSESBYCONFIGNAMERESPONSE_H
#define H12PRO_CONTROLLER_NODE_MESSAGE_CHANGEHANDARMPOSESBYCONFIGNAMERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace h12pro_controller_node
{
template <class ContainerAllocator>
struct changeHandArmPosesByConfigNameResponse_
{
  typedef changeHandArmPosesByConfigNameResponse_<ContainerAllocator> Type;

  changeHandArmPosesByConfigNameResponse_()
    : result(false)  {
    }
  changeHandArmPosesByConfigNameResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> const> ConstPtr;

}; // struct changeHandArmPosesByConfigNameResponse_

typedef ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<std::allocator<void> > changeHandArmPosesByConfigNameResponse;

typedef boost::shared_ptr< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse > changeHandArmPosesByConfigNameResponsePtr;
typedef boost::shared_ptr< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse const> changeHandArmPosesByConfigNameResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator1> & lhs, const ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator1> & lhs, const ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace h12pro_controller_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "h12pro_controller_node/changeHandArmPosesByConfigNameResponse";
  }

  static const char* value(const ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
"\n"
;
  }

  static const char* value(const ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct changeHandArmPosesByConfigNameResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::h12pro_controller_node::changeHandArmPosesByConfigNameResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // H12PRO_CONTROLLER_NODE_MESSAGE_CHANGEHANDARMPOSESBYCONFIGNAMERESPONSE_H
