// Generated by gencpp from file h12pro_controller_node/ExecuteArmActionRequest.msg
// DO NOT EDIT!


#ifndef H12PRO_CONTROLLER_NODE_MESSAGE_EXECUTEARMACTIONREQUEST_H
#define H12PRO_CONTROLLER_NODE_MESSAGE_EXECUTEARMACTIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace h12pro_controller_node
{
template <class ContainerAllocator>
struct ExecuteArmActionRequest_
{
  typedef ExecuteArmActionRequest_<ContainerAllocator> Type;

  ExecuteArmActionRequest_()
    : action_name()  {
    }
  ExecuteArmActionRequest_(const ContainerAllocator& _alloc)
    : action_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _action_name_type;
  _action_name_type action_name;





  typedef boost::shared_ptr< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteArmActionRequest_

typedef ::h12pro_controller_node::ExecuteArmActionRequest_<std::allocator<void> > ExecuteArmActionRequest;

typedef boost::shared_ptr< ::h12pro_controller_node::ExecuteArmActionRequest > ExecuteArmActionRequestPtr;
typedef boost::shared_ptr< ::h12pro_controller_node::ExecuteArmActionRequest const> ExecuteArmActionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator1> & lhs, const ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.action_name == rhs.action_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator1> & lhs, const ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace h12pro_controller_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4d9ec8eb1541d8a917c71ed6f9b1654";
  }

  static const char* value(const ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4d9ec8eb1541d8aULL;
  static const uint64_t static_value2 = 0x917c71ed6f9b1654ULL;
};

template<class ContainerAllocator>
struct DataType< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "h12pro_controller_node/ExecuteArmActionRequest";
  }

  static const char* value(const ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string action_name  # 要执行的动作名称，例如 \"welcome\"\n"
;
  }

  static const char* value(const ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteArmActionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::h12pro_controller_node::ExecuteArmActionRequest_<ContainerAllocator>& v)
  {
    s << indent << "action_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.action_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // H12PRO_CONTROLLER_NODE_MESSAGE_EXECUTEARMACTIONREQUEST_H
