// Generated by gencpp from file h12pro_controller_node/playmusic.msg
// DO NOT EDIT!


#ifndef H12PRO_CONTROLLER_NODE_MESSAGE_PLAYMUSIC_H
#define H12PRO_CONTROLLER_NODE_MESSAGE_PLAYMUSIC_H

#include <ros/service_traits.h>


#include <h12pro_controller_node/playmusicRequest.h>
#include <h12pro_controller_node/playmusicResponse.h>


namespace h12pro_controller_node
{

struct playmusic
{

typedef playmusicRequest Request;
typedef playmusicResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct playmusic
} // namespace h12pro_controller_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::h12pro_controller_node::playmusic > {
  static const char* value()
  {
    return "3d99283888736c5e18f20ac685e5f8bf";
  }

  static const char* value(const ::h12pro_controller_node::playmusic&) { return value(); }
};

template<>
struct DataType< ::h12pro_controller_node::playmusic > {
  static const char* value()
  {
    return "h12pro_controller_node/playmusic";
  }

  static const char* value(const ::h12pro_controller_node::playmusic&) { return value(); }
};


// service_traits::MD5Sum< ::h12pro_controller_node::playmusicRequest> should match
// service_traits::MD5Sum< ::h12pro_controller_node::playmusic >
template<>
struct MD5Sum< ::h12pro_controller_node::playmusicRequest>
{
  static const char* value()
  {
    return MD5Sum< ::h12pro_controller_node::playmusic >::value();
  }
  static const char* value(const ::h12pro_controller_node::playmusicRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::h12pro_controller_node::playmusicRequest> should match
// service_traits::DataType< ::h12pro_controller_node::playmusic >
template<>
struct DataType< ::h12pro_controller_node::playmusicRequest>
{
  static const char* value()
  {
    return DataType< ::h12pro_controller_node::playmusic >::value();
  }
  static const char* value(const ::h12pro_controller_node::playmusicRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::h12pro_controller_node::playmusicResponse> should match
// service_traits::MD5Sum< ::h12pro_controller_node::playmusic >
template<>
struct MD5Sum< ::h12pro_controller_node::playmusicResponse>
{
  static const char* value()
  {
    return MD5Sum< ::h12pro_controller_node::playmusic >::value();
  }
  static const char* value(const ::h12pro_controller_node::playmusicResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::h12pro_controller_node::playmusicResponse> should match
// service_traits::DataType< ::h12pro_controller_node::playmusic >
template<>
struct DataType< ::h12pro_controller_node::playmusicResponse>
{
  static const char* value()
  {
    return DataType< ::h12pro_controller_node::playmusic >::value();
  }
  static const char* value(const ::h12pro_controller_node::playmusicResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // H12PRO_CONTROLLER_NODE_MESSAGE_PLAYMUSIC_H
