// Generated by gencpp from file h12pro_controller_node/playmusicResponse.msg
// DO NOT EDIT!


#ifndef H12PRO_CONTROLLER_NODE_MESSAGE_PLAYMUSICRESPONSE_H
#define H12PRO_CONTROLLER_NODE_MESSAGE_PLAYMUSICRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace h12pro_controller_node
{
template <class ContainerAllocator>
struct playmusicResponse_
{
  typedef playmusicResponse_<ContainerAllocator> Type;

  playmusicResponse_()
    : success_flag(false)  {
    }
  playmusicResponse_(const ContainerAllocator& _alloc)
    : success_flag(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_flag_type;
  _success_flag_type success_flag;





  typedef boost::shared_ptr< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> const> ConstPtr;

}; // struct playmusicResponse_

typedef ::h12pro_controller_node::playmusicResponse_<std::allocator<void> > playmusicResponse;

typedef boost::shared_ptr< ::h12pro_controller_node::playmusicResponse > playmusicResponsePtr;
typedef boost::shared_ptr< ::h12pro_controller_node::playmusicResponse const> playmusicResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::h12pro_controller_node::playmusicResponse_<ContainerAllocator1> & lhs, const ::h12pro_controller_node::playmusicResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success_flag == rhs.success_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::h12pro_controller_node::playmusicResponse_<ContainerAllocator1> & lhs, const ::h12pro_controller_node::playmusicResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace h12pro_controller_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51d4deda6e3cbea57b8c79590b6cd9bb";
  }

  static const char* value(const ::h12pro_controller_node::playmusicResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51d4deda6e3cbea5ULL;
  static const uint64_t static_value2 = 0x7b8c79590b6cd9bbULL;
};

template<class ContainerAllocator>
struct DataType< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "h12pro_controller_node/playmusicResponse";
  }

  static const char* value(const ::h12pro_controller_node::playmusicResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success_flag\n"
"\n"
;
  }

  static const char* value(const ::h12pro_controller_node::playmusicResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct playmusicResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::h12pro_controller_node::playmusicResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::h12pro_controller_node::playmusicResponse_<ContainerAllocator>& v)
  {
    s << indent << "success_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // H12PRO_CONTROLLER_NODE_MESSAGE_PLAYMUSICRESPONSE_H
