// Generated by gencpp from file h12pro_controller_node/robotPhase.msg
// DO NOT EDIT!


#ifndef H12PRO_CONTROLLER_NODE_MESSAGE_ROBOTPHASE_H
#define H12PRO_CONTROLLER_NODE_MESSAGE_ROBOTPHASE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace h12pro_controller_node
{
template <class ContainerAllocator>
struct robotPhase_
{
  typedef robotPhase_<ContainerAllocator> Type;

  robotPhase_()
    : mainPhase(0)
    , subPhase(0)  {
    }
  robotPhase_(const ContainerAllocator& _alloc)
    : mainPhase(0)
    , subPhase(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mainPhase_type;
  _mainPhase_type mainPhase;

   typedef uint8_t _subPhase_type;
  _subPhase_type subPhase;





  typedef boost::shared_ptr< ::h12pro_controller_node::robotPhase_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::h12pro_controller_node::robotPhase_<ContainerAllocator> const> ConstPtr;

}; // struct robotPhase_

typedef ::h12pro_controller_node::robotPhase_<std::allocator<void> > robotPhase;

typedef boost::shared_ptr< ::h12pro_controller_node::robotPhase > robotPhasePtr;
typedef boost::shared_ptr< ::h12pro_controller_node::robotPhase const> robotPhaseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::h12pro_controller_node::robotPhase_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::h12pro_controller_node::robotPhase_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::h12pro_controller_node::robotPhase_<ContainerAllocator1> & lhs, const ::h12pro_controller_node::robotPhase_<ContainerAllocator2> & rhs)
{
  return lhs.mainPhase == rhs.mainPhase &&
    lhs.subPhase == rhs.subPhase;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::h12pro_controller_node::robotPhase_<ContainerAllocator1> & lhs, const ::h12pro_controller_node::robotPhase_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace h12pro_controller_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::h12pro_controller_node::robotPhase_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::h12pro_controller_node::robotPhase_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::h12pro_controller_node::robotPhase_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::h12pro_controller_node::robotPhase_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h12pro_controller_node::robotPhase_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h12pro_controller_node::robotPhase_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::h12pro_controller_node::robotPhase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26cd19545acfae4dd7729b92456b2c32";
  }

  static const char* value(const ::h12pro_controller_node::robotPhase_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26cd19545acfae4dULL;
  static const uint64_t static_value2 = 0xd7729b92456b2c32ULL;
};

template<class ContainerAllocator>
struct DataType< ::h12pro_controller_node::robotPhase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "h12pro_controller_node/robotPhase";
  }

  static const char* value(const ::h12pro_controller_node::robotPhase_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::h12pro_controller_node::robotPhase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mainPhase\n"
"uint8 subPhase\n"
;
  }

  static const char* value(const ::h12pro_controller_node::robotPhase_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::h12pro_controller_node::robotPhase_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mainPhase);
      stream.next(m.subPhase);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotPhase_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::h12pro_controller_node::robotPhase_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::h12pro_controller_node::robotPhase_<ContainerAllocator>& v)
  {
    s << indent << "mainPhase: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mainPhase);
    s << indent << "subPhase: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.subPhase);
  }
};

} // namespace message_operations
} // namespace ros

#endif // H12PRO_CONTROLLER_NODE_MESSAGE_ROBOTPHASE_H
