// Generated by gencpp from file h12pro_controller_node/srvChangePhasesResponse.msg
// DO NOT EDIT!


#ifndef H12PRO_CONTROLLER_NODE_MESSAGE_SRVCHANGEPHASESRESPONSE_H
#define H12PRO_CONTROLLER_NODE_MESSAGE_SRVCHANGEPHASESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace h12pro_controller_node
{
template <class ContainerAllocator>
struct srvChangePhasesResponse_
{
  typedef srvChangePhasesResponse_<ContainerAllocator> Type;

  srvChangePhasesResponse_()
    : stateRes(0)  {
    }
  srvChangePhasesResponse_(const ContainerAllocator& _alloc)
    : stateRes(0)  {
  (void)_alloc;
    }



   typedef int16_t _stateRes_type;
  _stateRes_type stateRes;





  typedef boost::shared_ptr< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srvChangePhasesResponse_

typedef ::h12pro_controller_node::srvChangePhasesResponse_<std::allocator<void> > srvChangePhasesResponse;

typedef boost::shared_ptr< ::h12pro_controller_node::srvChangePhasesResponse > srvChangePhasesResponsePtr;
typedef boost::shared_ptr< ::h12pro_controller_node::srvChangePhasesResponse const> srvChangePhasesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator1> & lhs, const ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.stateRes == rhs.stateRes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator1> & lhs, const ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace h12pro_controller_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7033fb042cc98da45f99da4d28b07c65";
  }

  static const char* value(const ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7033fb042cc98da4ULL;
  static const uint64_t static_value2 = 0x5f99da4d28b07c65ULL;
};

template<class ContainerAllocator>
struct DataType< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "h12pro_controller_node/srvChangePhasesResponse";
  }

  static const char* value(const ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 stateRes\n"
"\n"
;
  }

  static const char* value(const ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stateRes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvChangePhasesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::h12pro_controller_node::srvChangePhasesResponse_<ContainerAllocator>& v)
  {
    s << indent << "stateRes: ";
    Printer<int16_t>::stream(s, indent + "  ", v.stateRes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // H12PRO_CONTROLLER_NODE_MESSAGE_SRVCHANGEPHASESRESPONSE_H
