// Generated by gencpp from file kuavo_ros_interfaces/ocs2ChangeArmCtrlMode.msg
// DO NOT EDIT!


#ifndef KUAVO_ROS_INTERFACES_MESSAGE_OCS2CHANGEARMCTRLMODE_H
#define KUAVO_ROS_INTERFACES_MESSAGE_OCS2CHANGEARMCTRLMODE_H

#include <ros/service_traits.h>


#include <kuavo_ros_interfaces/ocs2ChangeArmCtrlModeRequest.h>
#include <kuavo_ros_interfaces/ocs2ChangeArmCtrlModeResponse.h>


namespace kuavo_ros_interfaces
{

struct ocs2ChangeArmCtrlMode
{

typedef ocs2ChangeArmCtrlModeRequest Request;
typedef ocs2ChangeArmCtrlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ocs2ChangeArmCtrlMode
} // namespace kuavo_ros_interfaces


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlMode > {
  static const char* value()
  {
    return "8a8d154c05ee16e8f5d2b72d9bb51026";
  }

  static const char* value(const ::kuavo_ros_interfaces::ocs2ChangeArmCtrlMode&) { return value(); }
};

template<>
struct DataType< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlMode > {
  static const char* value()
  {
    return "kuavo_ros_interfaces/ocs2ChangeArmCtrlMode";
  }

  static const char* value(const ::kuavo_ros_interfaces::ocs2ChangeArmCtrlMode&) { return value(); }
};


// service_traits::MD5Sum< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlModeRequest> should match
// service_traits::MD5Sum< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlMode >
template<>
struct MD5Sum< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlMode >::value();
  }
  static const char* value(const ::kuavo_ros_interfaces::ocs2ChangeArmCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlModeRequest> should match
// service_traits::DataType< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlMode >
template<>
struct DataType< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlModeRequest>
{
  static const char* value()
  {
    return DataType< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlMode >::value();
  }
  static const char* value(const ::kuavo_ros_interfaces::ocs2ChangeArmCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlModeResponse> should match
// service_traits::MD5Sum< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlMode >
template<>
struct MD5Sum< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlMode >::value();
  }
  static const char* value(const ::kuavo_ros_interfaces::ocs2ChangeArmCtrlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlModeResponse> should match
// service_traits::DataType< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlMode >
template<>
struct DataType< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlModeResponse>
{
  static const char* value()
  {
    return DataType< ::kuavo_ros_interfaces::ocs2ChangeArmCtrlMode >::value();
  }
  static const char* value(const ::kuavo_ros_interfaces::ocs2ChangeArmCtrlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUAVO_ROS_INTERFACES_MESSAGE_OCS2CHANGEARMCTRLMODE_H
