// Generated by gencpp from file kuavo_ros_interfaces/stopPlanArmTrajectoryRequest.msg
// DO NOT EDIT!


#ifndef KUAVO_ROS_INTERFACES_MESSAGE_STOPPLANARMTRAJECTORYREQUEST_H
#define KUAVO_ROS_INTERFACES_MESSAGE_STOPPLANARMTRAJECTORYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_ros_interfaces
{
template <class ContainerAllocator>
struct stopPlanArmTrajectoryRequest_
{
  typedef stopPlanArmTrajectoryRequest_<ContainerAllocator> Type;

  stopPlanArmTrajectoryRequest_()
    {
    }
  stopPlanArmTrajectoryRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct stopPlanArmTrajectoryRequest_

typedef ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<std::allocator<void> > stopPlanArmTrajectoryRequest;

typedef boost::shared_ptr< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest > stopPlanArmTrajectoryRequestPtr;
typedef boost::shared_ptr< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest const> stopPlanArmTrajectoryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace kuavo_ros_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_ros_interfaces/stopPlanArmTrajectoryRequest";
  }

  static const char* value(const ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stopPlanArmTrajectoryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::kuavo_ros_interfaces::stopPlanArmTrajectoryRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_ROS_INTERFACES_MESSAGE_STOPPLANARMTRAJECTORYREQUEST_H
