// Generated by gencpp from file kuavo_ros_interfaces/stopPlanArmTrajectoryResponse.msg
// DO NOT EDIT!


#ifndef KUAVO_ROS_INTERFACES_MESSAGE_STOPPLANARMTRAJECTORYRESPONSE_H
#define KUAVO_ROS_INTERFACES_MESSAGE_STOPPLANARMTRAJECTORYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kuavo_ros_interfaces
{
template <class ContainerAllocator>
struct stopPlanArmTrajectoryResponse_
{
  typedef stopPlanArmTrajectoryResponse_<ContainerAllocator> Type;

  stopPlanArmTrajectoryResponse_()
    : result(false)  {
    }
  stopPlanArmTrajectoryResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct stopPlanArmTrajectoryResponse_

typedef ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<std::allocator<void> > stopPlanArmTrajectoryResponse;

typedef boost::shared_ptr< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse > stopPlanArmTrajectoryResponsePtr;
typedef boost::shared_ptr< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse const> stopPlanArmTrajectoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator1> & lhs, const ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator1> & lhs, const ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kuavo_ros_interfaces

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kuavo_ros_interfaces/stopPlanArmTrajectoryResponse";
  }

  static const char* value(const ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
;
  }

  static const char* value(const ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stopPlanArmTrajectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kuavo_ros_interfaces::stopPlanArmTrajectoryResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KUAVO_ROS_INTERFACES_MESSAGE_STOPPLANARMTRAJECTORYRESPONSE_H
